import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'or', name: 'Odia', native: 'ଓଡ଼ିଆ' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'sat', name: 'Santhali', native: 'संथाली (Santali)' },
  { code: 'gon', name: 'Gondi', native: 'गोंडी (Gondi)' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
];

export const TRANSLATIONS = {
  en: {
    // Brand & System
    siteName: 'JanjatiSetu',
    siteNameRegional: 'JanjatiSetu',
    siteTagline: 'Unified Tribal Scholarship Portal',
    ministryName: 'Ministry of Tribal Affairs (MoTA)',
    govIndia: 'Government of India',
    dbtMissionCompliance: 'Direct Benefit Transfer (DBT) Mission & DPDP Act 2023 Compliant',
    roleSwitcher: 'Role Switcher',
    demoPersonas: '1-Click Demo Personas',
    demoSub: 'Test all 5 schemes & officer consoles',
    ninePersonas: '9 Personas',

    // Navigation & Mega Menu
    home: 'Home',
    schemes: 'Scholarship Schemes',
    predictorsTools: 'Predictors & Tools',
    wallet: 'DigiLocker Wallet',
    dbtTracker: 'PFMS DBT Tracker',
    grievance: 'Grievance & Appeals',
    officerConsole: 'Officer Console',
    applyForFY: 'Apply for FY26-27',
    askJago: 'Ask JAGO',
    signIn: 'Sign In',
    signOut: 'Log Out',
    profile: 'Profile',
    searchPlaceholder: 'Search 5 MoTA schemes, 246 IITs/IIMs, DigiLocker, PFMS DBT...',
    matchingResults: 'Matching Results',
    cantFindAskJago: "Can't find what you need? Ask JAGO Multilingual AI",

    // Mega menu dropdowns
    schoolHigherEd: 'School & Higher Education',
    fellowshipsAbroad: 'Fellowships & Global Studies',
    allowanceCalculator: 'Allowance Calculator',
    allowanceCalcSub: 'Calculate financial entitlement based on fee & hosteller status',
    schemeComparator: 'Scheme Comparator',
    schemeComparatorSub: 'Compare 2-3 MoTA scholarships side-by-side',
    digilockerVault: 'DigiLocker Vault',
    digilockerVaultSub: 'Zero-upload digital document verification',
    pfmsLedger: 'PFMS DBT Ledger',
    pfmsLedgerSub: 'Live Aadhaar APBS bank credit status',
    viewAllSchemesMatrix: 'View All 5 Schemes Matrix',

    // Hero Section (All 4 slides fully localized)
    heroBadge1: 'Academic Year 2026-27 Open',
    heroTitle1: 'JanjatiSetu • Unified Portal for Tribal Students',
    heroHighlight1: 'Empowering 38.5 Lakh+ ST Scholars Across India',
    heroDesc1: 'Single-window discovery and paperless application for all 5 official Ministry of Tribal Affairs (MoTA) schemes with instant DigiLocker e-KYC and conflict-free processing.',
    heroPrimary1: 'Explore 5 MoTA Schemes',
    heroSecondary1: 'DigiLocker Vault',
    heroFeat1_1: '100% Paperless DigiLocker',
    heroFeat1_2: 'Real-time PFMS DBT',
    heroFeat1_3: 'Zero Application Fee',
    heroFeat1_4: 'Multi-lingual JAGO AI',
    heroStatVal1: '₹1,420 Cr+',
    heroStatLbl1: 'Direct Benefit Transfer (DBT) via PFMS',

    heroBadge2: 'Top-Class Education • 246 Premier Institutes',
    heroTitle2: 'Full Tuition + ₹45,000 Laptop Grant',
    heroHighlight2: 'For IITs, IIMs, AIIMS, NITs & National Law Universities',
    heroDesc2: 'ST students admitted into notified premier institutes receive full tuition fee reimbursement, ₹36,000/yr living expenses, ₹5,000 book grant and a one-time ₹45,000 laptop entitlement.',
    heroPrimary2: 'Apply Top-Class Scheme',
    heroSecondary2: 'Check 246 Institutes',
    heroFeat2_1: '100% Non-Refundable Fees',
    heroFeat2_2: '₹36,000 Living Expenses',
    heroFeat2_3: '₹45,000 Laptop Grant',
    heroFeat2_4: 'Divyang Assistance',
    heroStatVal2: '246 Institutes',
    heroStatLbl2: 'Empanelled Premier Institutes across India',

    heroBadge3: 'National Overseas Scholarship (NOS)',
    heroTitle3: 'Study at Top 500 QS World Universities',
    heroHighlight3: 'Full Foreign Tuition + USD 15,400 Annual Allowance',
    heroDesc3: 'Pursue Master’s and Ph.D. degrees in premier universities abroad with airfare, medical insurance, visa fees, contingency grants and living allowances funded by MoTA.',
    heroPrimary3: 'Apply Overseas (NOS)',
    heroSecondary3: 'Compare Benefits',
    heroFeat3_1: 'Top 500 QS Universities',
    heroFeat3_2: '$15,400/yr (USA) • £9,900/yr (UK)',
    heroFeat3_3: 'Return Airfare Covered',
    heroFeat3_4: 'Full Visa & Health Cover',
    heroStatVal3: '$15,400/yr',
    heroStatLbl3: 'Annual Living Maintenance Allowance',

    heroBadge4: 'National Fellowship for ST Students (NFST)',
    heroTitle4: 'Doctoral Fellowship for ST Scholars',
    heroHighlight4: '₹31,000/mo JRF • ₹35,000/mo SRF + HRA & Contingency',
    heroDesc4: 'Merit-based financial assistance for Scheduled Tribe students pursuing regular M.Phil and Ph.D. research courses in UGC-recognized Indian Universities with zero income cap.',
    heroPrimary4: 'Apply NFST Fellowship',
    heroSecondary4: 'Ask JAGO AI',
    heroFeat4_1: 'No Family Income Ceiling',
    heroFeat4_2: '₹31,000 - ₹35,000/month',
    heroFeat4_3: 'Annual Contingency Grant',
    heroFeat4_4: 'PVTG Priority Quota',
    heroStatVal4: '₹35,000/mo',
    heroStatLbl4: 'Senior Research Fellowship (SRF)',

    verifiedGovtScheme: 'Verified Govt Scheme',
    appMode: 'Application Mode',
    onlinePwa: '100% Online (PWA)',
    disbChannel: 'Disbursement Channel',
    directApbsDbt: 'Direct APBS Bank DBT',
    docVerif: 'Doc Verification',
    digilockerPki: 'DigiLocker PKI e-KYC',
    slideOf: 'Slide',

    // Scheme Finder Widget
    findScholarshipTitle: 'Find Scholarship Schemes For You',
    findScholarshipSub: 'Filter across 5 MoTA Central Schemes in seconds • 100% Conflict-Free Matching',
    aiAssistedTag: 'AI-Assisted Eligibility Check',
    eduLevelLabel: '1. Education Level',
    stateLabel: '2. State / Region',
    tribalCatLabel: '3. Tribal Category & Special Group',
    incomeLabel: '4. Annual Family Income',
    checkMatchedBtn: 'Check Matched Schemes & Entitlement',
    quickFilters: 'Quick Filters:',

    // How It Works
    howItWorksBadge: 'Simple 3-Step Process',
    howItWorksTitle: 'How Tribal Students Get Funded',
    howItWorksSub: 'From digital document fetch to direct bank transfer — a streamlined, transparent journey designed for ST scholars and families.',
    step1Title: 'Profile & DigiLocker e-KYC',
    step1Sub: 'Zero Physical Paperwork',
    step1Desc: 'Link your Aadhaar securely via DigiLocker. The portal automatically pulls and cryptographically validates your ST Tribe Certificate, Family Income, and 10th/12th Marksheets from State e-District databases.',
    step1Action: 'Open DigiLocker Vault',
    step2Title: 'AI Scheme Match & Conflict Check',
    step2Sub: 'Statutory 1-Scheme Enforcement',
    step2Desc: 'Our eligibility engine verifies your AISHE institution, degree level, and income threshold. The real-time conflict prevention engine guarantees you never face duplicate claim rejections.',
    step2Action: 'Check 5 MoTA Schemes',
    step3Title: '1-Click Apply & PFMS Direct DBT',
    step3Sub: 'Aadhaar-Seeded Bank Credit',
    step3Desc: 'Submit in under 2 minutes. Institutional and State Nodal Officers process applications with non-blocking timelines. Once sanctioned, funds transfer directly to your bank account via PFMS.',
    step3Action: 'Track PFMS DBT Status',
    dpdpGuarTitle: 'Statutory Data Privacy & Non-Blocking Verification',
    dpdpGuarDesc: '12-digit Aadhaar numbers are never stored in plain text. Verification adapter timeouts never block student application submission.',

    // Discovery Categories
    browseByCohortBadge: 'Direct Scheme Discovery',
    browseByCohortTitle: 'Browse MoTA Scholarships by Cohort',
    browseByCohortDesc: 'Select your educational level to view tailored benefits, statutory eligibility, and application forms.',
    viewAllMatrixBtn: 'View All Schemes Matrix',
    applyNow: 'Apply Now',
    trendingTools: 'Trending Tools & Predictors:',

    // Data & Tools (Calculator)
    interactiveToolsBadge: 'Interactive Tools & Predictors',
    allowanceCalcTitle: 'Scholarship Allowance & Entitlement Calculator',
    allowanceCalcDesc: 'Estimate your total financial entitlement — including tuition reimbursement, monthly living allowance, book grants, and one-time ₹45,000 laptop aid.',
    financialSimulator: 'Financial Entitlement Simulator',
    financialSimSub: 'Real-time calculation as per MoTA financial rules',
    selectSchemeLabel: 'Select Scholarship Scheme',
    annualTuitionLabel: 'Annual Compulsory Course / Tuition Fee',
    hostellerOption: 'Hosteller (Living Away)',
    divyangOption: 'Divyang (40%+ Disability)',
    laptopOption: '₹45,000 Laptop Grant',
    totalEstAnnual: 'Total Estimated Annual Entitlement',
    tuitionSupport: 'Tuition Support',
    livingMaintenance: 'Living / Maintenance',
    bookStationery: 'Book & Stationery',
    hardwareLaptop: 'Hardware / Laptop',
    proceedClaim: 'Proceed with Claim',
    launchComparator: 'Launch Scheme Comparator',
    openDigitalWallet: 'Open Digital Wallet',

    // Trust / Stats Bar
    stat1Val: '5',
    stat1Lbl: 'Official MoTA Schemes',
    stat1Sub: 'Single-Window Discovery',
    stat2Val: '₹1,420+ Cr',
    stat2Lbl: 'Disbursed via PFMS DBT',
    stat2Sub: 'Direct to Bank Account',
    stat3Val: '38.5 Lakh+',
    stat3Lbl: 'Tribal Scholars Funded',
    stat3Sub: 'Across 36 States & UTs',
    stat4Val: '246',
    stat4Lbl: 'Premier Institutes',
    stat4Sub: 'IITs, IIMs, AIIMS, NITs',
    stat5Val: '100%',
    stat5Lbl: 'DigiLocker Verified',
    stat5Sub: 'Zero Manual Paper Upload',

    // News & Updates
    officialNoticesBadge: 'Official Notifications',
    latestNewsTitle: 'Latest News, Sanction Orders & Circulars',
    latestNewsDesc: 'Real-time administrative notices, PFMS DBT sanction ledgers, and deadline alerts directly from Shastri Bhawan, New Delhi.',
    liveTickerTag: 'LIVE TICKER',
    liveTickerText: '🔥 Fresh applications for Academic Year 2026-27 are now active on JanjatiSetu • DigiLocker e-KYC is mandatory for zero-document upload.',
    allNotices: 'All Notices',
    sanctionsDbt: 'Sanctions & DBT',
    deadlines: 'Deadlines',
    guidelines: 'Guidelines',
    viewNotice: 'View Notice',
    downloadPdf: 'Download PDF',
    searchAllSanctions: 'Search All Central Sanctions in PFMS Ledger',

    // Expert Help & Community
    assistanceBadge: 'Assistance & Community',
    expertHelpTitle: 'Expert Help & Student Discussion Forum',
    expertHelpDesc: 'Get instant answers in your native language through the JAGO AI Voice Assistant or connect directly with MoTA Nodal Officers and tribal peer scholars.',
    jagoCardTitle: 'JAGO (जागो) Tribal AI Assistant',
    jagoCardDesc: 'Ask questions via Speech-to-Text or chat in 8 Indian languages with tribal cultural greetings (Johar!).',
    launchVoiceAssistant: 'Launch Voice Assistant Now',
    nationalHelpdesk: 'National Tribal Helpdesk',
    tollFreeHotline: 'Toll-Free National Hotline',
    monSatTiming: 'Mon-Sat (9 AM - 6 PM)',
    directGrievanceDesk: 'Direct Grievance Desk',
    fileAppeal: 'File Appeal',
    recentAnswersTitle: 'Recent Verified Answers',
    askQuestionBtn: 'Ask a Question',
    askModalTitle: 'Ask MoTA Nodal Officer & Community',
    askModalDesc: 'Post your query regarding eligibility, DigiLocker verification, or PFMS DBT bank transfers.',
    submitQuery: 'Submit Query',

    // FAQ Accordion
    faqBadge: 'Frequently Asked Questions',
    faqTitle: 'Common Questions & Rules Explained',
    faqDesc: 'Clear guidelines on Central MoTA eligibility, DigiLocker integration, and PFMS DBT payments.',
    searchFaqPlaceholder: 'Search FAQ by keyword (e.g. laptop, income, DigiLocker, PFMS, bank)...',
    allCategories: 'All Categories',
    eligibilityRulesTab: 'Eligibility & Rules',
    digilockerDocsTab: 'DigiLocker & Docs',
    topClassLaptopTab: 'Top Class & Laptop',
    pfmsBankTab: 'PFMS DBT & Bank',
    overseasNosTab: 'Overseas NOS',
    stillHaveQuestions: 'Still have questions about your application?',
    askJagoVoiceAi: 'Ask JAGO Voice AI',

    // Login & End-to-End Encryption
    loginTitle: 'Secure Portal Access',
    loginSubtitle: 'Ministry of Tribal Affairs (MoTA) • Government of India',
    loginBadgeOnePortal: 'Unified Single Portal for All 5 MoTA Schemes',
    tabMobileOtp: 'Student Mobile OTP',
    tabApaarDigi: 'APAAR / DigiLocker ID',
    tabOfficerAishe: 'Officer AISHE / Admin',
    e2eeBadge: 'E2EE Cryptographic Handshake Active (TLS 1.3 • AES-256-GCM)',
    e2eeNotice: 'All authentication packets are encrypted at rest and in transit. DPDP Act 2023 Certified.',
    mobileInputLabel: 'Mobile Number (Aadhaar / DBT Linked)',
    mobilePlaceholder: 'Enter 10-digit mobile number',
    enterOtpLabel: 'Enter 6-Digit Secure OTP',
    otpSentNotice: 'A one-time authorization OTP was dispatched to',
    didNotReceiveOtp: "Didn't receive OTP?",
    resendOtpIn: 'Resend in',
    resendOtpNow: 'Resend OTP Now',
    submitOtpVerify: 'Authorize & Sign In Securely',
    sendOtpBtn: 'Generate Secure OTP',
    useDevOtp: 'Use Instant Authorization OTP',
    apaarInputLabel: '12-Digit APAAR / EduID Number',
    apaarPlaceholder: 'e.g. 1234-5678-9012',
    apaarAuthNotice: 'APAAR links directly with your Academic Bank of Credits and DigiLocker documents.',
    apaarVerifyBtn: 'Authenticate via DigiLocker PKI',
    aisheCodeLabel: 'Institution AISHE Code / Directorate ID',
    aishePlaceholder: 'e.g. U-0306 (IIT Bombay)',
    officerPasswordLabel: 'Officer Encryption Password',
    securityPinLabel: '2FA e-Gov Security PIN',
    officerLoginBtn: 'Login to Officer Review Console',
    orQuickDemoPersonas: 'Or 1-Click Demo Evaluation Personas',

    // Footer
    footerMinistry: 'MINISTRY OF TRIBAL AFFAIRS',
    footerGovt: 'Government of India • जनजातीय कार्य मंत्रालय',
    footerAbout: 'JanjatiSetu - Unified Single-Window Scholarship Discovery & Disbursement Platform for Scheduled Tribe (ST) students across India. Empowering scholars with zero-paperwork DigiLocker e-KYC and direct PFMS bank transfer.',
    dpdpCompliant: 'DPDP Act 2023 Compliant',
    dpdpEncDesc: 'Zero raw Aadhaar storage • AES-256-GCM encryption',
    integratedPortals: 'Integrated National Portals',
    helpdeskContact: 'Helpdesk & Contact',
    downloadMobileApp: 'Download Mobile App',
    installPwa: 'Install Mobile PWA',
    allRightsReserved: 'Ministry of Tribal Affairs (MoTA), Government of India. All Rights Reserved.',
    grievanceRedressal: 'Grievance Redressal',
    privacyPolicy: 'Privacy Policy (DPDP Act)',
    accessibilityStatement: 'Accessibility Statement',
    termsConditions: 'Terms & Conditions'
  },

  hi: {
    // Brand & System
    siteName: 'जनजाति सेतु',
    siteNameRegional: 'JanjatiSetu',
    siteTagline: 'एकीकृत जनजातीय छात्रवृत्ति पोर्टल',
    ministryName: 'जनजातीय कार्य मंत्रालय (MoTA)',
    govIndia: 'भारत सरकार',
    dbtMissionCompliance: 'प्रत्यक्ष लाभ अंतरण (DBT) मिशन एवं DPDP अधिनियम 2023 अनुपालित',
    roleSwitcher: 'भूमिका बदलें (Role Switcher)',
    demoPersonas: '1-क्लिक डेमो व्यक्तित्व',
    demoSub: 'सभी 5 योजनाएं एवं अधिकारी कंसोल देखें',
    ninePersonas: '9 व्यक्तित्व',

    // Navigation & Mega Menu
    home: 'मुख्यपृष्ठ',
    schemes: 'छात्रवृत्ति योजनाएं',
    predictorsTools: 'कैलकुलेटर एवं टूल्स',
    wallet: 'डिजिलॉकर वॉलेट',
    dbtTracker: 'पीएफएमएस डीबीटी ट्रैकर',
    grievance: 'शिकायत एवं अपील',
    officerConsole: 'अधिकारी कंसोल',
    applyForFY: 'सत्र 2026-27 के लिए आवेदन करें',
    askJago: 'जागो से पूछें',
    signIn: 'लॉग इन करें',
    signOut: 'लॉग आउट',
    profile: 'प्रोफ़ाइल',
    searchPlaceholder: '5 MoTA योजनाएं, 246 IITs/IIMs, डिजिलॉकर, PFMS DBT खोजें...',
    matchingResults: 'समान परिणाम',
    cantFindAskJago: 'अपनी मनचाही जानकारी नहीं मिली? जागो (JAGO) बहुभाषी AI से पूछें',

    // Mega menu dropdowns
    schoolHigherEd: 'स्कूली एवं उच्च शिक्षा',
    fellowshipsAbroad: 'फैलोशिप एवं विदेश अध्ययन',
    allowanceCalculator: 'भत्ता एवं पात्रता कैलकुलेटर',
    allowanceCalcSub: 'शुल्क और हॉस्टल स्थिति के आधार पर वित्तीय पात्रता जानें',
    schemeComparator: 'योजना तुलना टूल',
    schemeComparatorSub: 'एक साथ 2-3 MoTA योजनाओं की तुलना करें',
    digilockerVault: 'डिजिलॉकर डिजिटल वॉल्ट',
    digilockerVaultSub: 'शून्य दस्तावेज़ अपलोड - सीधा डिजिटल सत्यापन',
    pfmsLedger: 'पीएफएमएस डीबीटी लेजर',
    pfmsLedgerSub: 'आधार लिंक बैंक खाते में राशि की स्थिति देखें',
    viewAllSchemesMatrix: 'सभी 5 योजनाओं का विवरण देखें',

    // Hero Section
    heroBadge1: 'शैक्षणिक सत्र 2026-27 खुला है',
    heroTitle1: 'जनजाति सेतु • जनजातीय छात्रों का एकीकृत पोर्टल',
    heroHighlight1: 'भारत भर के 38.5 लाख+ अनुसूचित जनजाति छात्रों का सशक्तिकरण',
    heroDesc1: 'जनजातीय कार्य मंत्रालय की सभी 5 आधिकारिक छात्रवृत्ति योजनाओं के लिए एकल खिड़की खोज एवं डिजिलॉकर ई-केवाईसी द्वारा पेपरलेस आवेदन।',
    heroPrimary1: 'सभी 5 योजनाएं देखें',
    heroSecondary1: 'डिजिलॉकर वॉल्ट',
    heroFeat1_1: '100% पेपरलेस डिजिलॉकर',
    heroFeat1_2: 'सीधा PFMS बैंक अंतरण',
    heroFeat1_3: 'निःशुल्क आवेदन',
    heroFeat1_4: 'बहुभाषी जागो (JAGO) AI',
    heroStatVal1: '₹1,420 करोड़+',
    heroStatLbl1: 'PFMS द्वारा प्रत्यक्ष लाभ अंतरण (DBT)',

    heroBadge2: 'शीर्ष श्रेणी शिक्षा • 246 प्रमुख संस्थान',
    heroTitle2: 'पूर्ण शिक्षण शुल्क + ₹45,000 लैपटॉप अनुदान',
    heroHighlight2: 'IIT, IIM, AIIMS, NIT और राष्ट्रीय विधि विश्वविद्यालयों के लिए',
    heroDesc2: 'प्रमुख संस्थानों में अध्ययनरत एसटी छात्रों को 100% फीस प्रतिपूर्ति, ₹36,000/वर्ष निर्वाह भत्ता, ₹5,000 पुस्तक अनुदान एवं ₹45,000 का लैपटॉप अनुदान।',
    heroPrimary2: 'टॉप-क्लास योजना में आवेदन करें',
    heroSecondary2: '246 संस्थानों की सूची देखें',
    heroFeat2_1: '100% गैर-वापसी योग्य फीस',
    heroFeat2_2: '₹36,000 निर्वाह भत्ता',
    heroFeat2_3: '₹45,000 लैपटॉप सहायता',
    heroFeat2_4: 'दिव्यांग विशेष अनुदान',
    heroStatVal2: '246 संस्थान',
    heroStatLbl2: 'देशभर में सूचीबद्ध शीर्ष संस्थान',

    heroBadge3: 'राष्ट्रीय विदेशी छात्रवृत्ति (NOS)',
    heroTitle3: 'विश्व के शीर्ष 500 QS विश्वविद्यालयों में अध्ययन',
    heroHighlight3: 'पूर्ण विदेशी फीस + $15,400 वार्षिक निर्वाह भत्ता',
    heroDesc3: 'विदेश में मास्टर और पीएचडी हेतु हवाई किराया, स्वास्थ्य बीमा, वीजा शुल्क एवं मासिक निर्वाह अनुदान भारत सरकार द्वारा वहन किया जाता है।',
    heroPrimary3: 'विदेशी छात्रवृत्ति (NOS) आवेदन',
    heroSecondary3: 'लाभों की तुलना करें',
    heroFeat3_1: 'शीर्ष 500 QS संस्थान',
    heroFeat3_2: '$15,400/वर्ष (USA) • £9,900/वर्ष (UK)',
    heroFeat3_3: 'आने-जाने का हवाई किराया',
    heroFeat3_4: 'पूर्ण वीजा व स्वास्थ्य बीमा',
    heroStatVal3: '$15,400/वर्ष',
    heroStatLbl3: 'वार्षिक निर्वाह भत्ता अनुदान',

    heroBadge4: 'राष्ट्रीय फैलोशिप (NFST)',
    heroTitle4: 'एसटी शोधार्थियों के लिए डॉक्टरेट फैलोशिप',
    heroHighlight4: '₹31,000/माह JRF • ₹35,000/माह SRF + HRA व आकस्मिक अनुदान',
    heroDesc4: 'यूजीसी मान्यता प्राप्त विश्वविद्यालयों में नियमित एम.फिल एवं पीएचडी शोधार्थियों हेतु बिना किसी पारिवारिक आय सीमा के योग्यता आधारित फैलोशिप।',
    heroPrimary4: 'NFST फैलोशिप आवेदन',
    heroSecondary4: 'जागो AI से पूछें',
    heroFeat4_1: 'कोई पारिवारिक आय सीमा नहीं',
    heroFeat4_2: '₹31,000 - ₹35,000 प्रति माह',
    heroFeat4_3: 'वार्षिक आकस्मिक अनुदान',
    heroFeat4_4: 'PVTG विशेष प्राथमिकता कोटा',
    heroStatVal4: '₹35,000/माह',
    heroStatLbl4: 'सीनियर रिसर्च फैलोशिप (SRF)',

    verifiedGovtScheme: 'सत्यापित सरकारी योजना',
    appMode: 'आवेदन माध्यम',
    onlinePwa: '100% ऑनलाइन (PWA)',
    disbChannel: 'भुगतान माध्यम',
    directApbsDbt: 'सीधा बैंक खाता (DBT)',
    docVerif: 'दस्तावेज़ सत्यापन',
    digilockerPki: 'डिजिलॉकर ई-केवाईसी',
    slideOf: 'स्लाइड',

    // Scheme Finder Widget
    findScholarshipTitle: 'अपने लिए उपयुक्त छात्रवृत्ति खोजें',
    findScholarshipSub: 'सेकंडों में 5 MoTA योजनाओं में खोजें • 100% टकराव-मुक्त मिलान',
    aiAssistedTag: 'AI-सहायता प्राप्त पात्रता जांच',
    eduLevelLabel: '1. शिक्षा का स्तर',
    stateLabel: '2. राज्य / केंद्र शासित प्रदेश',
    tribalCatLabel: '3. जनजातीय श्रेणी एवं विशेष समूह',
    incomeLabel: '4. वार्षिक पारिवारिक आय',
    checkMatchedBtn: 'पात्र योजनाएं एवं वित्तीय लाभ जांचें',
    quickFilters: 'त्वरित फ़िल्टर:',

    // How It Works
    howItWorksBadge: 'सरल 3-चरणीय प्रक्रिया',
    howItWorksTitle: 'छात्रवृत्ति प्राप्त करने की आसान प्रक्रिया',
    howItWorksSub: 'डिजिटल दस्तावेज़ सत्यापन से सीधे बैंक खाते में भुगतान तक — एसटी छात्रों के लिए पारदर्शी व्यवस्था।',
    step1Title: 'प्रोफ़ाइल एवं डिजिलॉकर ई-केवाईसी',
    step1Sub: 'शून्य कागजी कार्रवाई',
    step1Desc: 'आधार को डिजिलॉकर से लिंक करें। पोर्टल आपके राज्य ई-डिस्ट्रिक्ट डेटाबेस से जाति, आय और अंकतालिका को स्वतः सत्यापित करता है।',
    step1Action: 'डिजिलॉकर वॉल्ट खोलें',
    step2Title: 'AI योजना मिलान एवं टकराव जांच',
    step2Sub: 'एक-योजना नियम का पालन',
    step2Desc: 'हमारा सिस्टम आपके संस्थान, पाठ्यक्रम और आय की जांच कर सुनिश्चित करता है कि दोहरा आवेदन न हो।',
    step2Action: '5 MoTA योजनाएं देखें',
    step3Title: '1-क्लिक आवेदन और PFMS सीधा DBT',
    step3Sub: 'आधार लिंक बैंक खाते में भुगतान',
    step3Desc: '2 मिनट में आवेदन जमा करें। स्वीकृति के बाद छात्रवृत्ति राशि सीधे आपके बैंक खाते में PFMS द्वारा भेजी जाती है।',
    step3Action: 'PFMS DBT स्थिति ट्रैक करें',
    dpdpGuarTitle: 'डेटा गोपनीयता एवं निरंतर सत्यापन गारंटी',
    dpdpGuarDesc: '12-अंकों का आधार नंबर कभी भी सादे टेक्स्ट में सुरक्षित नहीं किया जाता। सर्वर धीमा होने पर भी आवेदन नहीं रुकता।',

    // Discovery Categories
    browseByCohortBadge: 'सीधी योजना खोज',
    browseByCohortTitle: 'कक्षा एवं श्रेणी अनुसार छात्रवृत्ति देखें',
    browseByCohortDesc: 'अपने शिक्षा स्तर का चयन करें और लाभ, पात्रता व आवेदन पत्र देखें।',
    viewAllMatrixBtn: 'सभी योजनाओं का मैट्रिक्स देखें',
    applyNow: 'आवेदन करें',
    trendingTools: 'ट्रेंडिंग टूल्स व कैलकुलेटर:',

    // Data & Tools (Calculator)
    interactiveToolsBadge: 'इंटरैक्टिव टूल्स एवं प्रेडिक्टर्स',
    allowanceCalcTitle: 'छात्रवृत्ति भत्ता एवं वित्तीय पात्रता कैलकुलेटर',
    allowanceCalcDesc: 'फीस प्रतिपूर्ति, मासिक निर्वाह भत्ता, पुस्तक अनुदान और ₹45,000 लैपटॉप सहायता की सटीक गणना करें।',
    financialSimulator: 'वित्तीय पात्रता सिमुलेटर',
    financialSimSub: 'MoTA के नियमों के अनुसार सटीक गणना',
    selectSchemeLabel: 'छात्रवृत्ति योजना चुनें',
    annualTuitionLabel: 'वार्षिक अनिवार्य पाठ्यक्रम / ट्यूशन शुल्क',
    hostellerOption: 'छात्रावासी (Hosteller)',
    divyangOption: 'दिव्यांग (40%+ दिव्यांगता)',
    laptopOption: '₹45,000 लैपटॉप अनुदान',
    totalEstAnnual: 'कुल अनुमानित वार्षिक पात्रता',
    tuitionSupport: 'शिक्षण शुल्क सहायता',
    livingMaintenance: 'निर्वाह भत्ता (Living)',
    bookStationery: 'पुस्तक व लेखन सामग्री',
    hardwareLaptop: 'हार्डवेयर / लैपटॉप',
    proceedClaim: 'आवेदन के लिए आगे बढ़ें',
    launchComparator: 'योजना तुलना टूल खोलें',
    openDigitalWallet: 'डिजिटल वॉलेट खोलें',

    // Trust / Stats Bar
    stat1Val: '5',
    stat1Lbl: 'आधिकारिक MoTA योजनाएं',
    stat1Sub: 'एकल खिड़की मंच',
    stat2Val: '₹1,420+ करोड़',
    stat2Lbl: 'PFMS द्वारा डीबीटी भुगतान',
    stat2Sub: 'सीधे बैंक खाते में',
    stat3Val: '38.5 लाख+',
    stat3Lbl: 'लाभान्वित जनजातीय छात्र',
    stat3Sub: '36 राज्यों व केंद्र शासित प्रदेशों में',
    stat4Val: '246',
    stat4Lbl: 'प्रमुख संस्थान',
    stat4Sub: 'IIT, IIM, AIIMS, NIT',
    stat5Val: '100%',
    stat5Lbl: 'डिजिलॉकर सत्यापित',
    stat5Sub: 'शून्य कागजी अपलोड',

    // News & Updates
    officialNoticesBadge: 'आधिकारिक सूचनाएं',
    latestNewsTitle: 'नवीनतम समाचार, स्वीकृति आदेश एवं परिपत्र',
    latestNewsDesc: 'शास्त्री भवन, नई दिल्ली से सीधे प्रशासनिक सूचनाएं, PFMS स्वीकृति लेजर एवं समय-सीमा अलर्ट।',
    liveTickerTag: 'लाइव टिकर',
    liveTickerText: '🔥 सत्र 2026-27 के लिए जनजाति सेतु पर सभी 5 योजनाओं के नए आवेदन शुरू हो चुके हैं • डिजिलॉकर ई-केवाईसी अनिवार्य है।',
    allNotices: 'सभी सूचनाएं',
    sanctionsDbt: 'स्वीकृति एवं डीबीटी',
    deadlines: 'समय सीमाएं',
    guidelines: 'दिशानिर्देश',
    viewNotice: 'सूचना देखें',
    downloadPdf: 'पीडीएफ डाउनलोड करें',
    searchAllSanctions: 'पीएफएमएस लेजर में सभी स्वीकृतियां खोजें',

    // Expert Help & Community
    assistanceBadge: 'सहायता एवं समुदाय',
    expertHelpTitle: 'विशेषज्ञ सहायता एवं छात्र परिचर्चा मंच',
    expertHelpDesc: 'जागो (JAGO) AI वॉयस असिस्टेंट द्वारा अपनी भाषा में तुरंत उत्तर पाएं या नोडल अधिकारियों से सीधे जुड़ें।',
    jagoCardTitle: 'जागो (JAGO) जनजातीय AI सहायक',
    jagoCardDesc: '8 भारतीय भाषाओं में वॉयस या चैट द्वारा अपनी मूल भाषा में प्रश्न पूछें (जोहार!)।',
    launchVoiceAssistant: 'वॉयस असिस्टेंट शुरू करें',
    nationalHelpdesk: 'राष्ट्रीय जनजातीय हेल्पलाइन',
    tollFreeHotline: 'टोल-फ्री राष्ट्रीय हेल्पलाइन',
    monSatTiming: 'सोम-शनि (सुबह 9 - शाम 6)',
    directGrievanceDesk: 'प्रत्यक्ष शिकायत निवारण डेस्क',
    fileAppeal: 'अपील दर्ज करें',
    recentAnswersTitle: 'हाल के सत्यापित उत्तर',
    askQuestionBtn: 'प्रश्न पूछें',
    askModalTitle: 'अधिकारी एवं समुदाय से प्रश्न पूछें',
    askModalDesc: 'पात्रता, डिजिलॉकर सत्यापन या PFMS डीबीटी बैंक अंतरण संबंधी प्रश्न दर्ज करें।',
    submitQuery: 'प्रश्न जमा करें',

    // FAQ Accordion
    faqBadge: 'अक्सर पूछे जाने वाले प्रश्न',
    faqTitle: 'सामान्य प्रश्न एवं नियमों का स्पष्टीकरण',
    faqDesc: 'MoTA पात्रता, डिजिलॉकर और PFMS DBT बैंक भुगतान पर स्पष्ट दिशानिर्देश।',
    searchFaqPlaceholder: 'कीवर्ड द्वारा खोजें (उदा. लैपटॉप, आय, डिजिलॉकर, बैंक)...',
    allCategories: 'सभी श्रेणियां',
    eligibilityRulesTab: 'पात्रता एवं नियम',
    digilockerDocsTab: 'डिजिलॉकर एवं दस्तावेज',
    topClassLaptopTab: 'टॉप क्लास एवं लैपटॉप',
    pfmsBankTab: 'PFMS DBT एवं बैंक',
    overseasNosTab: 'विदेशी छात्रवृत्ति (NOS)',
    stillHaveQuestions: 'क्या आपके आवेदन के संबंध में कोई अन्य प्रश्न है?',
    askJagoVoiceAi: 'जागो AI से पूछें',

    // Login & E2EE
    loginTitle: 'सुरक्षित पोर्टल लॉगिन (E2EE)',
    loginSubtitle: 'जनजातीय कार्य मंत्रालय (MoTA) • भारत सरकार',
    loginBadgeOnePortal: 'सभी 5 MoTA योजनाओं के लिए एकल अधिकृत खिड़की',
    tabMobileOtp: 'छात्र मोबाइल ओटीपी',
    tabApaarDigi: 'अपार (APAAR) / डिजिलॉकर',
    tabOfficerAishe: 'अधिकारी AISHE / नोडल',
    e2eeBadge: 'सुरक्षित E2EE क्रिप्टोग्राफिक सत्र सक्रिय (TLS 1.3 • AES-256-GCM)',
    e2eeNotice: 'सभी ऑथेंटिकेशन पैकेट क्लाइंट साइड पर एन्क्रिप्ट किए जाते हैं। DPDP अधिनियम 2023 प्रमाणित।',
    mobileInputLabel: 'मोबाइल नंबर (आधार / DBT लिंक)',
    mobilePlaceholder: '10 अंकों का मोबाइल नंबर दर्ज करें',
    enterOtpLabel: '6 अंकों का सुरक्षित OTP दर्ज करें',
    otpSentNotice: 'एक सुरक्षित अधिकृत OTP भेजा गया है:',
    didNotReceiveOtp: 'OTP प्राप्त नहीं हुआ?',
    resendOtpIn: 'पुनः भेजें:',
    resendOtpNow: 'अभी OTP पुनः भेजें',
    submitOtpVerify: 'सुरक्षित रूप से सत्यापित व लॉगिन करें',
    sendOtpBtn: 'सुरक्षित OTP प्राप्त करें',
    useDevOtp: 'त्वरित डेमो OTP का उपयोग करें',
    apaarInputLabel: '12 अंकों का APAAR / EduID नंबर',
    apaarPlaceholder: 'उदा. 1234-5678-9012',
    apaarAuthNotice: 'APAAR आपके एकेडमिक बैंक ऑफ क्रेडिट्स और डिजिलॉकर से सीधे जुड़ा है।',
    apaarVerifyBtn: 'डिजिलॉकर PKI द्वारा सत्यापित करें',
    aisheCodeLabel: 'संस्थान AISHE कोड / निदेशालय आईडी',
    aishePlaceholder: 'उदा. U-0306 (IIT बॉम्बे)',
    officerPasswordLabel: 'अधिकारी एन्क्रिप्शन पासवर्ड',
    securityPinLabel: '2FA ई-गवर्नेंस सुरक्षा पिन',
    officerLoginBtn: 'समीक्षा कंसोल में लॉगिन करें',
    orQuickDemoPersonas: 'या 1-क्लिक डेमो व्यक्तित्व द्वारा लॉगिन करें',

    // Footer
    footerMinistry: 'जनजातीय कार्य मंत्रालय',
    footerGovt: 'भारत सरकार • Ministry of Tribal Affairs',
    footerAbout: 'जनजाति सेतु (JanjatiSetu) - भारत भर के अनुसूचित जनजाति (ST) छात्रों के लिए एकल खिड़की छात्रवृत्ति खोज एवं वितरण मंच। पेपरलेस डिजिलॉकर ई-केवाईसी और सीधे बैंक खाते में PFMS अंतरण।',
    dpdpCompliant: 'DPDP अधिनियम 2023 अनुपालित',
    dpdpEncDesc: 'शून्य कच्चा आधार भंडारण • AES-256-GCM एन्क्रिप्शन',
    integratedPortals: 'एकीकृत राष्ट्रीय पोर्टल',
    helpdeskContact: 'हेल्पलाइन एवं संपर्क',
    downloadMobileApp: 'मोबाइल ऐप डाउनलोड करें',
    installPwa: 'मोबाइल PWA इंस्टॉल करें',
    allRightsReserved: 'जनजातीय कार्य मंत्रालय, भारत सरकार। सर्वाधिकार सुरक्षित।',
    grievanceRedressal: 'शिकायत निवारण',
    privacyPolicy: 'गोपनीयता नीति (DPDP Act)',
    accessibilityStatement: 'पहुंच क्षमता विवरण',
    termsConditions: 'नियम एवं शर्तें'
  },

  or: {
    siteName: 'ଜନଜାତି ସେତୁ',
    siteNameRegional: 'JanjatiSetu',
    siteTagline: 'ୟୁନିଫାଏଡ୍ ଜନଜାତି ଛାତ୍ରବୃତ୍ତି ପୋର୍ଟାଲ୍',
    ministryName: 'ଜନଜାତି କାର୍ଯ୍ୟ ମନ୍ତ୍ରଣାଳୟ (MoTA)',
    govIndia: 'ଭାରତ ସରକାର',
    dbtMissionCompliance: 'ପ୍ରତ୍ୟକ୍ଷ ଲାଭ ହସ୍ତାନ୍ତର (DBT) ଓ DPDP ଆଇନ ୨୦୨୩ ଅନୁମୋଦିତ',
    roleSwitcher: 'ଭୂମିକା ପରିବର୍ତ୍ତନ (Role Switcher)',
    demoPersonas: '୧-କ୍ଲିକ୍ ଡେମୋ ପର୍ସନା',
    demoSub: 'ସମସ୍ତ ୫ଟି ଯୋଜନା ଓ ଅଫିସର କନସୋଲ୍ ଯାଞ୍ଚ କରନ୍ତୁ',
    ninePersonas: '୯ ପର୍ସନା',

    home: 'ମୂଳପୃଷ୍ଠା',
    schemes: 'ଛାତ୍ରବୃତ୍ତି ଯୋଜନା',
    predictorsTools: 'କାଲକୁଲେଟର ଓ ଟୁଲ୍ସ',
    wallet: 'ଡିଜିଲକର ୱାଲେଟ୍',
    dbtTracker: 'PFMS DBT ଟ୍ରାକର୍',
    grievance: 'ଅଭିଯୋଗ ଓ ଅପିଲ୍',
    officerConsole: 'ଅଫିସର୍ କନସୋଲ୍',
    applyForFY: '୨୦୨୬-୨୭ ପାଇଁ ଆବେଦନ କରନ୍ତୁ',
    askJago: 'ଜାଗୋକୁ ପଚାରନ୍ତୁ',
    signIn: 'ସାଇନ୍ ଇନ୍',
    signOut: 'ଲଗ୍ ଆଉଟ୍',
    profile: 'ପ୍ରୋଫାଇଲ୍',
    searchPlaceholder: 'MoTA ଯୋଜନା, ୨୪୬ IITs/IIMs, ଡିଜିଲକର, PFMS ଖୋଜନ୍ତୁ...',
    matchingResults: 'ମେଳ ଖାଉଥିବା ଫଳାଫଳ',
    cantFindAskJago: 'ଜାଗୋ (JAGO) AI କୁ ପଚାରନ୍ତୁ',

    heroBadge1: 'ଶିକ୍ଷାବର୍ଷ ୨୦୨୬-୨୭ ଖୋଲା ଅଛି',
    heroTitle1: 'ଜନଜାତି ସେତୁ • ଆଦିବାସୀ ଛାତ୍ରବୃତ୍ତି ପୋର୍ଟାଲ୍',
    heroHighlight1: 'ସମଗ୍ର ଭାରତର ୩୮.୫ ଲକ୍ଷରୁ ଅଧିକ ST ଛାତ୍ରଛାତ୍ରୀଙ୍କ ସଶକ୍ତୀକରଣ',
    heroDesc1: 'ଜନଜାତି କାର୍ଯ୍ୟ ମନ୍ତ୍ରଣାଳୟର ସମସ୍ତ ୫ଟି ଯୋଜନାରେ ଡିଜିଲକର ଇ-କେୱାଇସି ମାଧ୍ୟମରେ କାଗଜପତ୍ର ବିହୀନ ଆବେଦନ।',
    heroPrimary1: '୫ଟି ଯୋଜନା ଦେଖନ୍ତୁ',
    heroSecondary1: 'ଡିଜିଲକର ଭଣ୍ଡାର',
    heroFeat1_1: '୧୦୦% କାଗଜବିହୀନ ଡିଜିଲକର',
    heroFeat1_2: 'ସିଧାସଳଖ PFMS ବ୍ୟାଙ୍କ ଜମା',
    heroFeat1_3: 'ମାଗଣା ଆବେଦନ',
    heroFeat1_4: 'ବହୁଭାଷୀ ଜାଗୋ (JAGO) AI',
    heroStatVal1: '₹୧,୪୨୦ କୋଟି+',
    heroStatLbl1: 'PFMS ମାଧ୍ୟମରେ ସିଧାସଳଖ ବ୍ୟାଙ୍କ ଟଙ୍କା ପ୍ରଦାନ (DBT)',

    heroBadge2: 'ଶୀର୍ଷ ଶ୍ରେଣୀ ଶିକ୍ଷା • ୨୪୬ ପ୍ରମୁଖ ଅନୁଷ୍ଠାନ',
    heroTitle2: 'ସମ୍ପୂର୍ଣ୍ଣ ଫିସ୍ + ₹୪୫,୦୦୦ ଲାପଟପ୍ ଅନୁଦାନ',
    heroHighlight2: 'IIT, IIM, AIIMS, NIT ଏବଂ ଜାତୀୟ ଆଇନ ବିଶ୍ୱବିଦ୍ୟାଳୟ ପାଇଁ',
    heroDesc2: 'ପ୍ରମୁଖ ଅନୁଷ୍ଠାନରେ ପଢ଼ୁଥିବା ST ଛାତ୍ରଛାତ୍ରୀଙ୍କୁ ୧୦୦% ଫିସ୍, ₹୩୬,୦୦୦ ବାର୍ଷିକ ଖର୍ଚ୍ଚ ଏବଂ ₹୪୫,୦୦୦ ଲାପଟପ୍ ଅନୁଦାନ।',
    heroPrimary2: 'ଟପ୍-କ୍ଲାସ୍ ଆବେଦନ କରନ୍ତୁ',
    heroSecondary2: '୨୪୬ ଅନୁଷ୍ଠାନ ତାଲିକା',
    heroFeat2_1: '୧୦୦% ସମ୍ପୂର୍ଣ୍ଣ ଫିସ୍ ଫେରସ୍ତ',
    heroFeat2_2: '₹୩୬,୦୦୦ ବାର୍ଷିକ ଖର୍ଚ୍ଚ',
    heroFeat2_3: '₹୪୫,୦୦୦ ଲାପଟପ୍ ଅନୁଦାନ',
    heroFeat2_4: 'ଦିବ୍ୟାଙ୍ଗ ସହାୟତା',
    heroStatVal2: '୨୪୬ ଅନୁଷ୍ଠାନ',
    heroStatLbl2: 'ଦେଶର ପ୍ରମୁଖ ଅନୁଷ୍ଠାନ ସମୂହ',

    heroBadge3: 'ଜାତୀୟ ବିଦେଶୀ ଛାତ୍ରବୃତ୍ତି (NOS)',
    heroTitle3: 'ବିଶ୍ୱର ଶୀର୍ଷ ୫୦୦ QS ବିଶ୍ୱବିଦ୍ୟାଳୟରେ ଅଧ୍ୟୟନ',
    heroHighlight3: 'ସମ୍ପୂର୍ଣ୍ଣ ବିଦେଶୀ ଫିସ୍ + $୧୫,୪୦୦ ବାର୍ଷିକ ଖର୍ଚ୍ଚ',
    heroDesc3: 'ମାଷ୍ଟର୍ସ ଓ ପିଏଚଡି ପାଇଁ ବିମାନ ଭଡ଼ା, ଭିସା ଫିସ୍ ଓ ସ୍ୱାସ୍ଥ୍ୟ ବୀମା ଭାରତ ସରକାର ବହନ କରିବେ।',
    heroPrimary3: 'ବିଦେଶୀ ଛାତ୍ରବୃତ୍ତି (NOS) ଆବେଦନ',
    heroSecondary3: 'ସୁବିଧା ତୁଳନା କରନ୍ତୁ',
    heroFeat3_1: 'ଶୀର୍ଷ ୫୦୦ QS ବିଶ୍ୱବିଦ୍ୟାଳୟ',
    heroFeat3_2: '$୧୫,୪୦୦/ବର୍ଷ (USA) • £୯,୯୦୦/ବର୍ଷ (UK)',
    heroFeat3_3: 'ଯିବା-ଆସିବା ବିମାନ ଭଡ଼ା',
    heroFeat3_4: 'ଭିସା ଓ ସ୍ୱାସ୍ଥ୍ୟ ବୀମା',
    heroStatVal3: '$୧୫,୪୦୦/ବର୍ଷ',
    heroStatLbl3: 'ବାର୍ଷିକ ରହିବା ଖର୍ଚ୍ଚ ଭତ୍ତା',

    heroBadge4: 'ଜାତୀୟ ଫେଲୋସିପ୍ (NFST)',
    heroTitle4: 'ST ଗବେଷକମାନଙ୍କ ପାଇଁ ଡକ୍ଟରାଲ୍ ଫେଲୋସିପ୍',
    heroHighlight4: '₹୩୧,୦୦୦/ମାସ JRF • ₹୩୫,୦୦୦/ମାସ SRF + HRA',
    heroDesc4: 'ୟୁଜିସି ମାନ୍ୟତାପ୍ରାପ୍ତ ବିଶ୍ୱବିଦ୍ୟାଳୟରେ ନିୟମିତ ଏମ୍.ଫିଲ୍ ଓ ପିଏଚଡି ପାଇଁ ବିନା ଆୟ ସୀମାରେ ମେରିଟ୍ ଫେଲୋସିପ୍।',
    heroPrimary4: 'NFST ଫେଲୋସିପ୍ ଆବେଦନ',
    heroSecondary4: 'ଜାଗୋ AI କୁ ପଚାରନ୍ତୁ',
    heroFeat4_1: 'କୌଣସି ପାରିବାରିକ ଆୟ ସୀମା ନାହିଁ',
    heroFeat4_2: '₹୩୧,୦୦୦ - ₹୩୫,୦୦୦ ମାସିକ',
    heroFeat4_3: 'ବାର୍ଷିକ ଆନୁଷଙ୍ଗିକ ଅନୁଦାନ',
    heroFeat4_4: 'PVTG ସ୍ୱତନ୍ତ୍ର କୋଟା',
    heroStatVal4: '₹୩୫,୦୦୦/ମାସ',
    heroStatLbl4: 'ସିନିୟର ରିସର୍ଚ୍ଚ ଫେଲୋସିପ୍ (SRF)',

    verifiedGovtScheme: 'ଯାଞ୍ଚ ହୋଇଥିବା ସରକାରୀ ଯୋଜନା',
    appMode: 'ଆବେଦନ ମାଧ୍ୟମ',
    onlinePwa: '୧୦୦% ଅନଲାଇନ୍ (PWA)',
    disbChannel: 'ଟଙ୍କା ପ୍ରଦାନ ମାଧ୍ୟମ',
    directApbsDbt: 'ସିଧାସଳଖ ବ୍ୟାଙ୍କ ଜମା (DBT)',
    docVerif: 'ପ୍ରମାଣପତ୍ର ଯାଞ୍ଚ',
    digilockerPki: 'ଡିଜିଲକର e-KYC',
    slideOf: 'ସ୍ଲାଇଡ୍',

    loginTitle: 'ସୁରକ୍ଷିତ ପୋର୍ଟାଲ୍ ଲଗଇନ୍ (E2EE)',
    loginSubtitle: 'ଜନଜାତି କାର୍ଯ୍ୟ ମନ୍ତ୍ରଣାଳୟ (MoTA) • ଭାରତ ସରକାର',
    loginBadgeOnePortal: 'ସମସ୍ତ ୫ଟି MoTA ଯୋଜନା ପାଇଁ ଏକକ ସୁରକ୍ଷିତ ୱିଣ୍ଡୋ',
    tabMobileOtp: 'ଛାତ୍ର ମୋବାଇଲ୍ OTP',
    tabApaarDigi: 'APAAR / ଡିଜିଲକର',
    tabOfficerAishe: 'ଅଫିସର AISHE / ଆଡମିନ୍',
    e2eeBadge: 'E2EE ଏନକ୍ରିପ୍ଟେଡ୍ ସେସନ୍ ସକ୍ରିୟ (TLS 1.3 • AES-256-GCM)',
    e2eeNotice: 'ସମସ୍ତ ତଥ୍ୟ ସୁରକ୍ଷିତ ଏନକ୍ରିପ୍ସନ୍ ଦ୍ୱାରା ପ୍ରେରଣ କରାଯାଏ। DPDP ଆଇନ ୨୦୨୩ ପ୍ରମାଣିତ।',
    mobileInputLabel: 'ମୋବାଇଲ୍ ନମ୍ବର (ଆଧାର / DBT ଲିଙ୍କ୍)',
    mobilePlaceholder: '୧୦ ଅଙ୍କର ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ',
    enterOtpLabel: '୬ ଅଙ୍କର ସୁରକ୍ଷିତ OTP ଦିଅନ୍ତୁ',
    otpSentNotice: 'ଏକ ସୁରକ୍ଷିତ OTP ପ୍ରେରଣ କରାଯାଇଛି:',
    didNotReceiveOtp: 'OTP ପାଇଲେ ନାହିଁ କି?',
    resendOtpIn: 'ପୁନଃ ପ୍ରେରଣ:',
    resendOtpNow: 'ଏବେ OTP ପୁନଃ ପ୍ରେରଣ କରନ୍ତୁ',
    submitOtpVerify: 'ସୁରକ୍ଷିତ ଭାବେ ଲଗଇନ୍ କରନ୍ତୁ',
    sendOtpBtn: 'ସୁରକ୍ଷିତ OTP ମାଗନ୍ତୁ',
    useDevOtp: 'ଡେମୋ OTP ବ୍ୟବହାର କରନ୍ତୁ',
    apaarInputLabel: '୧୨ ଅଙ୍କର APAAR / EduID ନମ୍ବର',
    apaarPlaceholder: 'ଉଦା. 1234-5678-9012',
    apaarAuthNotice: 'APAAR ସିଧାସଳଖ ଆକାଡେମିକ୍ ବ୍ୟାଙ୍କ ଓ ଡିଜିଲକର ସହିତ ସଂଯୁକ୍ତ।',
    apaarVerifyBtn: 'ଡିଜିଲକର ଦ୍ୱାରା ଯାଞ୍ଚ କରନ୍ତୁ',
    aisheCodeLabel: 'ଅନୁଷ୍ଠାନ AISHE କୋଡ୍ / ID',
    aishePlaceholder: 'ଉଦା. U-0306 (IIT Bombay)',
    officerPasswordLabel: 'ଅଫିସର ଏନକ୍ରିପ୍ସନ୍ ପାସୱାର୍ଡ',
    securityPinLabel: '2FA ଇ-ଗଭର୍ଣ୍ଣାନ୍ସ ସୁରକ୍ଷା ପିନ୍',
    officerLoginBtn: 'ସମୀକ୍ଷା କନସୋଲ୍ ଲଗଇନ୍',
    orQuickDemoPersonas: 'କିମ୍ବା ୧-କ୍ଲିକ୍ ଡେମୋ ପର୍ସନା ବାଛନ୍ତୁ',

    findScholarshipTitle: 'ନିଜ ପାଇଁ ଉପଯୁକ୍ତ ଛାତ୍ରବୃତ୍ତି ଖୋଜନ୍ତୁ',
    findScholarshipSub: 'ସେକେଣ୍ଡରେ ୫ଟି ଯୋଜନା ଯାଞ୍ଚ କରନ୍ତୁ',
    aiAssistedTag: 'AI ଯୋଗ୍ୟତା ଯାଞ୍ଚ',
    eduLevelLabel: '୧. ଶିକ୍ଷାଗତ ଯୋଗ୍ୟତା',
    stateLabel: '୨. ରାଜ୍ୟ / କ୍ଷେତ୍ର',
    tribalCatLabel: '୩. ଆଦିବାସୀ ବର୍ଗ',
    incomeLabel: '୪. ବାର୍ଷିକ ପାରିବାରିକ ଆୟ',
    checkMatchedBtn: 'ଯୋଗ୍ୟ ଯୋଜନା ଯାଞ୍ଚ କରନ୍ତୁ',
    quickFilters: 'କ୍ୱିକ୍ ଫିଲ୍ଟର୍:',

    allowanceCalcTitle: 'ଛାତ୍ରବୃତ୍ତି ଭତ୍ତା ଓ ଆର୍ଥିକ ଯୋଗ୍ୟତା କାଲକୁଲେଟର',
    allowanceCalcDesc: 'ସମ୍ପୂର୍ଣ୍ଣ ଫିସ୍, ମାସିକ ଖର୍ଚ୍ଚ ଏବଂ ₹୪୫,୦୦୦ ଲାପଟପ୍ ଅନୁଦାନ ହିସାବ କରନ୍ତୁ।',
    totalEstAnnual: 'ମୋଟ ଆନୁମାନିକ ବାର୍ଷିକ ଅନୁଦାନ',
    tuitionSupport: 'ପାଠପଢ଼ା ଫିସ୍ ସହାୟତା',
    livingMaintenance: 'ମାସିକ ଖର୍ଚ୍ଚ / ଭତ୍ତା',
    hardwareLaptop: 'ଲାପଟପ୍ / ହାର୍ଡୱେର୍',
    proceedClaim: 'ଆବେଦନ ଆଗକୁ ବଢ଼ାନ୍ତୁ',
    launchComparator: 'ଯୋଜନା ତୁଳନା ଟୁଲ୍',

    stat1Val: '୫',
    stat1Lbl: 'MoTA ଅଫିସିଆଲ୍ ଯୋଜନା',
    stat1Sub: 'ସିଙ୍ଗଲ୍-ୱିଣ୍ଡୋ ମଞ୍ଚ',
    stat2Val: '₹୧,୪୨୦+ କୋଟି',
    stat2Lbl: 'PFMS DBT ପ୍ରଦାନ',
    stat2Sub: 'ସିଧାସଳଖ ବ୍ୟାଙ୍କ ଖାତାକୁ',
    stat3Val: '୩୮.୫ ଲକ୍ଷ+',
    stat3Lbl: 'ଉପକୃତ ଆଦିବାସୀ ଛାତ୍ରଛାତ୍ରୀ',
    stat3Sub: '୩୬ଟି ରାଜ୍ୟ ଓ କେନ୍ଦ୍ରଶାସିତ ଅଞ୍ଚଳ',
    stat4Val: '୨୪୬',
    stat4Lbl: 'ପ୍ରମୁଖ ଅନୁଷ୍ଠାନ',
    stat4Sub: 'IIT, IIM, AIIMS, NIT',
    stat5Val: '୧୦୦%',
    stat5Lbl: 'ଡିଜିଲକର ଯାଞ୍ଚ ହୋଇଛି',
    stat5Sub: 'କାଗଜପତ୍ର ବିହୀନ',

    jagoCardTitle: 'ଜାଗୋ (JAGO) ଆଦିବାସୀ AI ସହାୟକ',
    jagoCardDesc: 'ଓଡ଼ିଆ ଓ ଅନ୍ୟାନ୍ୟ ଭାଷାରେ ଭଏସ୍ କିମ୍ବା ଚାଟ୍ ମାଧ୍ୟମରେ ପଚାରନ୍ତୁ (ଜୋହାର!)।',
    launchVoiceAssistant: 'ଭଏସ୍ ଆସିଷ୍ଟାଣ୍ଟ୍ ଆରମ୍ଭ କରନ୍ତୁ',
    faqTitle: 'ସାଧାରଣ ପ୍ରଶ୍ନ ଓ ନିୟମାବଳୀ',
    faqDesc: 'MoTA ଯୋଗ୍ୟତା, ଡିଜିଲକର ଏବଂ PFMS DBT ବ୍ୟାଙ୍କ ଜମା ସମ୍ବନ୍ଧରେ ବିସ୍ତୃତ ସୂଚନା।',
    allCategories: 'ସମସ୍ତ ଶ୍ରେଣୀ',

    footerMinistry: 'ଜନଜାତି କାର୍ଯ୍ୟ ମନ୍ତ୍ରଣାଳୟ',
    footerGovt: 'ଭାରତ ସରକାର • Government of India',
    footerAbout: 'ଜନଜାତି ସେତୁ (JanjatiSetu) - ସମଗ୍ର ଭାରତର ଅନୁସୂଚିତ ଜନଜାତି (ST) ଛାତ୍ରଛାତ୍ରୀଙ୍କ ପାଇଁ ଏକକ ଛାତ୍ରବୃତ୍ତି ପୋର୍ଟାଲ୍। ଡିଜିଲକର ଇ-କେୱାଇସି ଓ PFMS ସିଧାସଳଖ ବ୍ୟାଙ୍କ ଜମା।',
    dpdpCompliant: 'DPDP ଆଇନ ୨୦୨୩ ଅନୁମୋଦିତ',
    allRightsReserved: 'ଜନଜାତି କାର୍ଯ୍ୟ ମନ୍ତ୍ରଣାଳୟ, ଭାରତ ସରକାର। ସର୍ବସ୍ୱତ୍ୱ ସଂରକ୍ଷିତ।'
  },

  bn: {
    siteName: 'জনজাতি সেতু',
    siteNameRegional: 'JanjatiSetu',
    siteTagline: 'একীকৃত উপজাতি বৃত্তি পোর্টাল',
    ministryName: 'উপজাতি বিষয়ক মন্ত্রক (MoTA)',
    govIndia: 'ভারত সরকার',
    dbtMissionCompliance: 'সরাসরি সুবিধা হস্তান্তর (DBT) ও DPDP আইন ২০২৩ অনুগত',
    roleSwitcher: 'ভূমিকা পরিবর্তন',
    demoPersonas: '১-ক্লিক ডেমো ভূমিকা',
    demoSub: 'সকল ৫টি স্কিম ও অফিসার কনসোল দেখুন',
    ninePersonas: '৯টি ভূমিকা',

    home: 'হোম',
    schemes: 'বৃত্তি প্রকল্পসমূহ',
    predictorsTools: 'টুলস ও ক্যালকুলেটর',
    wallet: 'ডিজিলকার ওয়ালেট',
    dbtTracker: 'PFMS DBT ট্র্যাকার',
    grievance: 'অভিযোগ ও আবেদন',
    officerConsole: 'অফিসার কনসোল',
    applyForFY: '২০২৬-২৭ শিক্ষাবর্ষে আবেদন করুন',
    askJago: 'জাগো কে জিজ্ঞাসা করুন',
    signIn: 'সাইন ইন',
    signOut: 'লগ আউট',
    profile: 'প্রোফাইল',
    searchPlaceholder: '৫টি MoTA স্কিম, ২৪৬টি IIT/IIM, ডিজিলকার খুঁজুন...',
    matchingResults: 'ম্যাচিং ফলাফল',

    heroBadge1: 'শিক্ষাবর্ষ ২০২৬-২৭ আবেদন উন্মুক্ত',
    heroTitle1: 'জনজাতি সেতু • উপজাতি ছাত্রদের একীকৃত পোর্টাল',
    heroHighlight1: 'ভারত জুড়ে ৩৮.৫ লক্ষ+ উপজাতি ছাত্রছাত্রীদের ক্ষমতায়ন',
    heroDesc1: 'উপজাতি বিষয়ক মন্ত্রকের সকল ৫টি অফিসিয়াল বৃত্তির জন্য পেপারলেস ডিজিলকার ই-কেওয়াইসি সহ একক উইন্ডো আবেদন।',
    heroPrimary1: '৫টি স্কিম দেখুন',
    heroSecondary1: 'ডিজিলকার ভল্ট',
    heroFeat1_1: '১০০% পেপারলেস ডিজিলকার',
    heroFeat1_2: 'সরাসরি PFMS ব্যাংক স্থানান্তর',
    heroFeat1_3: 'বিনামূল্যে আবেদন',
    heroFeat1_4: 'বহুভাষিক জাগো (JAGO) AI',
    heroStatVal1: '₹১,৪২০ কোটি+',
    heroStatLbl1: 'PFMS মারফত সরাসরি ব্যাংক একাউন্টে প্রদান (DBT)',

    heroBadge2: 'শীর্ষ শিক্ষা • ২৪৬টি প্রধান প্রতিষ্ঠান',
    heroTitle2: 'সম্পূর্ণ ফি + ₹৪৫,০০০ ল্যাপটপ অনুদান',
    heroHighlight2: 'IIT, IIM, AIIMS, NIT ও জাতীয় আইন বিশ্ববিদ্যালয়ের জন্য',
    heroDesc2: 'শীর্ষ প্রতিষ্ঠানে অধ্যয়নরত এসটি শিক্ষার্থীদের জন্য ১০০% ফি ফেরত, ₹৩৬,০০০ বার্ষিক ভাতা এবং ₹৪৫,০০০ ল্যাপটপ সহায়তা।',
    heroPrimary2: 'টপ-ক্লাস আবেদন করুন',
    heroSecondary2: '২৪৬ প্রতিষ্ঠানের তালিকা',
    heroFeat2_1: '১০০% সম্পূর্ণ ফি ফেরত',
    heroFeat2_2: '₹৩৬,০০০ বার্ষিক থাকার ভাতা',
    heroFeat2_3: '₹৪৫,০০০ ল্যাপটপ অনুদান',
    heroFeat2_4: 'প্রতিবন্ধী বিশেষ সহায়তা',
    heroStatVal2: '২৪৬ প্রতিষ্ঠান',
    heroStatLbl2: 'তালিকাভুক্ত শীর্ষ প্রতিষ্ঠান',

    heroBadge3: 'জাতীয় বিদেশী বৃত্তি (NOS)',
    heroTitle3: 'বিশ্বের শীর্ষ ৫০০ QS বিশ্ববিদ্যালয়ে পড়াশোনা',
    heroHighlight3: 'সম্পূর্ণ বিদেশী ফি + $১৫,৪০০ বার্ষিক ভাতা',
    heroDesc3: 'মাস্টার্স ও পিএইচডি গবেষণার জন্য বিমান ভাড়া, ভিসা ফি ও স্বাস্থ্য বীমা সম্পূর্ণ ভারত সরকার প্রদান করে।',
    heroPrimary3: 'বিদেশী বৃত্তি (NOS) আবেদন',
    heroSecondary3: 'সুবিধা তুলনা করুন',
    heroFeat3_1: 'শীর্ষ ৫০০ QS বিশ্ববিদ্যালয়',
    heroFeat3_2: '$১৫,৪০০/বছর (USA) • £৯,৯০০/বছর (UK)',
    heroFeat3_3: 'আসা-যাওয়ার বিমান ভাড়া',
    heroFeat3_4: 'সম্পূর্ণ ভিসা ও স্বাস্থ্য কভার',
    heroStatVal3: '$১৫,৪০০/বছর',
    heroStatLbl3: 'বার্ষিক জীবনযাত্রা ভাতা',

    heroBadge4: 'জাতীয় ফেলোশিপ (NFST)',
    heroTitle4: 'এসটি গবেষকদের জন্য ডক্টরাল ফেলোশিপ',
    heroHighlight4: '₹৩১,০০০/মাস JRF • ₹৩৫,০০০/মাস SRF + HRA',
    heroDesc4: 'ইউজিসি স্বীকৃত বিশ্ববিদ্যালয়ে এম.ফিল ও পিএইচডি গবেষণার জন্য কোনো পারিবারিক আয়সীমা ছাড়া মেধাভিত্তিক ফেলোশিপ।',
    heroPrimary4: 'NFST ফেলোশিপ আবেদন',
    heroSecondary4: 'জাগো AI কে জিজ্ঞাসা করুন',
    heroFeat4_1: 'কোনো পারিবারিক আয়সীমা নেই',
    heroFeat4_2: '₹৩১,০০০ - ₹৩৫,০০০ প্রতি মাসে',
    heroFeat4_3: 'বার্ষিক কন্টিনজেন্সি অনুদান',
    heroFeat4_4: 'PVTG বিশেষ কোটা',
    heroStatVal4: '₹৩৫,০০০/মাস',
    heroStatLbl4: 'সিনিয়র রিসার্চ ফেলোশিপ (SRF)',

    verifiedGovtScheme: 'যাচাইকৃত সরকারি প্রকল্প',
    appMode: 'আবেদন পদ্ধতি',
    onlinePwa: '১০০% অনলাইন (PWA)',
    disbChannel: 'অর্থ প্রদান চ্যানেল',
    directApbsDbt: 'সরাসরি ব্যাংক একাউন্টে (DBT)',
    docVerif: 'নথি যাচাই',
    digilockerPki: 'ডিজিলকার e-KYC',
    slideOf: 'স্লাইড',

    loginTitle: 'নিরাপদ পোর্টাল লগইন (E2EE)',
    loginSubtitle: 'উপজাতি বিষয়ক মন্ত্রক (MoTA) • ভারত সরকার',
    loginBadgeOnePortal: 'সকল ৫টি MoTA স্কিমের জন্য একক সমন্বিত পোর্টাল',
    tabMobileOtp: 'ছাত্র মোবাইল OTP',
    tabApaarDigi: 'আপার (APAAR) / ডিজিলকার',
    tabOfficerAishe: 'অফিসার AISHE / অ্যাডমিন',
    e2eeBadge: 'E2EE এনক্রিপ্ট সেশন সক্রিয় (TLS 1.3 • AES-256-GCM)',
    e2eeNotice: 'সকল প্রমাণীকরণ প্যাকেট সুরক্ষিতভাবে প্রেরণ করা হয়। DPDP আইন ২০২৩ প্রত্যয়িত।',
    mobileInputLabel: 'মোবাইল নম্বর (আধার / DBT যুক্ত)',
    mobilePlaceholder: '১০ সংখ্যার মোবাইল নম্বর লিখুন',
    enterOtpLabel: '৬ সংখ্যার সুরক্ষিত OTP লিখুন',
    otpSentNotice: 'একটি এককালীন সুরক্ষিত OTP পাঠানো হয়েছে:',
    didNotReceiveOtp: 'OTP পাননি?',
    resendOtpIn: 'পুনরায় পাঠান:',
    resendOtpNow: 'এখনই OTP পাঠান',
    submitOtpVerify: 'সুরক্ষিতভাবে যাচাই ও লগইন করুন',
    sendOtpBtn: 'সুরক্ষিত OTP পান',
    useDevOtp: 'ডেমো OTP ব্যবহার করুন',
    apaarInputLabel: '১২ সংখ্যার APAAR / EduID নম্বর',
    apaarPlaceholder: 'উদা. 1234-5678-9012',
    apaarAuthNotice: 'APAAR সরাসরি একাডেমিক ব্যাংক ও ডিজিলকারের সাথে যুক্ত।',
    apaarVerifyBtn: 'ডিজিলকার দিয়ে যাচাই করুন',
    aisheCodeLabel: 'প্রতিষ্ঠান AISHE কোড / আইডি',
    aishePlaceholder: 'উদা. U-0306 (IIT Bombay)',
    officerPasswordLabel: 'অফিসার এনক্রিপশন পাসওয়ার্ড',
    securityPinLabel: '2FA ই-গভর্নেন্স সুরক্ষা পিন',
    officerLoginBtn: 'রিভিউ কনসোলে লগইন করুন',
    orQuickDemoPersonas: 'অথবা ১-ক্লিক ডেমো ভূমিকা নির্বাচন করুন',

    findScholarshipTitle: 'আপনার জন্য উপযুক্ত বৃত্তি খুঁজুন',
    findScholarshipSub: 'কয়েক সেকেন্ডে ৫টি MoTA স্কিম পরীক্ষা করুন',
    aiAssistedTag: 'AI योग्यता যাচাই',
    eduLevelLabel: '১. শিক্ষাগত যোগ্যতা',
    stateLabel: '২. রাজ্য / অঞ্চল',
    tribalCatLabel: '৩. উপজাতি শ্রেণী',
    incomeLabel: '৪. বার্ষিক পারিবারিক আয়',
    checkMatchedBtn: 'উপযুক্ত স্কিম পরীক্ষা করুন',

    allowanceCalcTitle: 'বৃত্তি ভাতা ও আর্থিক এনটাইটেলমেন্ট ক্যালকুলেটর',
    allowanceCalcDesc: 'সম্পূর্ণ ফি, মাসিক থাকার ভাতা এবং ₹৪৫,০০০ ল্যাপটপ অনুদান গণনা করুন।',
    totalEstAnnual: 'মোট আনুমানিক বার্ষিক এনটাইটেলমেন্ট',
    tuitionSupport: 'টিউশন ফি সহায়তা',
    livingMaintenance: 'থাকার / রক্ষণাবেক্ষণ ভাতা',
    hardwareLaptop: 'হার্ডওয়্যার / ল্যাপটপ অনুদান',
    proceedClaim: 'আবেদনে এগিয়ে যান',
    launchComparator: 'স্কিম তুলনা টুল',

    stat1Val: '৫',
    stat1Lbl: 'অফিসিয়াল MoTA স্কিম',
    stat1Sub: 'একক উইন্ডো প্ল্যাটফর্ম',
    stat2Val: '₹১,৪২০+ কোটি',
    stat2Lbl: 'PFMS DBT মারফত প্রদত্ত',
    stat2Sub: 'সরাসরি ব্যাংক অ্যাকাউন্টে',
    stat3Val: '৩৮.৫ লক্ষ+',
    stat3Lbl: 'উপকৃত উপজাতি শিক্ষার্থী',
    stat3Sub: '৩৬টি রাজ্য ও কেন্দ্রশাসিত অঞ্চল',
    stat4Val: '২৪৬',
    stat4Lbl: 'শীর্ষ প্রতিষ্ঠান',
    stat4Sub: 'IIT, IIM, AIIMS, NIT',
    stat5Val: '১০০%',
    stat5Lbl: 'ডিজিলকার যাচাইকৃত',
    stat5Sub: 'পেপারলেস আবেদন',

    footerMinistry: 'উপজাতি বিষয়ক মন্ত্রক',
    footerGovt: 'ভারত সরকার • Government of India',
    footerAbout: 'জনজাতি সেতু (JanjatiSetu) - ভারতের তফসিলি উপজাতি (ST) শিক্ষার্থীদের জন্য একক পোর্টাল। ডিজিলকার ও PFMS সরাসরি ব্যাংক স্থানান্তর।',
    allRightsReserved: 'উপজাতি বিষয়ক মন্ত্রক, ভারত সরকার। সর্বস্বত্ব সংরক্ষিত।'
  },

  mr: {
    siteName: 'जनजाती सेतू',
    siteNameRegional: 'JanjatiSetu',
    siteTagline: 'एकीकृत आदिवासी शिष्यवृत्ती पोर्टल',
    ministryName: 'आदिवासी कार्य मंत्रालय (MoTA)',
    govIndia: 'भारत सरकार',
    dbtMissionCompliance: 'थेट लाभ हस्तांतरण (DBT) मिशन व DPDP कायदा २०२३ अनुपालित',
    roleSwitcher: 'भूमिका बदला',
    demoPersonas: '१-क्लिक डेमो भूमिका',
    demoSub: 'सर्व ५ योजना आणि अधिकारी कन्सोल तपासा',
    ninePersonas: '९ भूमिका',

    home: 'मुख्यपृष्ठ',
    schemes: 'शिष्यवृत्ती योजना',
    predictorsTools: 'कॅल्क्युलेटर व टूल्स',
    wallet: 'डिजीलॉकर वॉलेट',
    dbtTracker: 'PFMS DBT ट्रॅकर',
    grievance: 'तक्रार निवारण',
    officerConsole: 'अधिकारी कन्सोल',
    applyForFY: 'सत्र २०२६-२७ साठी अर्ज करा',
    askJago: 'जागोला विचारा',
    signIn: 'साइन इन',
    signOut: 'लॉग आउट',
    profile: 'प्रोफाइल',
    searchPlaceholder: 'MoTA योजना, २४६ IIT/IIM, डिजीलॉकर शोधा...',
    matchingResults: 'जुळणारे निकाल',

    heroBadge1: 'शैक्षणिक वर्ष २०२६-२७ खुले आहे',
    heroTitle1: 'जनजाती सेतू • आदिवासी विद्यार्थ्यांसाठी एकीकृत पोर्टल',
    heroHighlight1: 'भारतभरातील ३८.५ लाख+ आदिवासी विद्यार्थ्यांचे सक्षमीकरण',
    heroDesc1: 'आदिवासी कार्य मंत्रालयाच्या सर्व ५ अधिकृत योजनांसाठी डिजीलॉकर ई-केवायसी द्वारे पेपरलेस अर्ज.',
    heroPrimary1: '५ योजना पहा',
    heroSecondary1: 'डिजीलॉकर वॉल्ट',
    heroFeat1_1: '१००% पेपरलेस डिजीलॉकर',
    heroFeat1_2: 'थेट PFMS बँक खात्यात जमा',
    heroFeat1_3: 'विनामूल्य अर्ज',
    heroFeat1_4: 'बहुभाषिक जागो (JAGO) AI',
    heroStatVal1: '₹१,४२० कोटी+',
    heroStatLbl1: 'PFMS द्वारे थेट बँक खात्यात वितरण (DBT)',

    heroBadge2: 'शीर्ष श्रेणी शिक्षण • २४६ प्रमुख संस्था',
    heroTitle2: 'पूर्ण शिक्षण शुल्क + ₹४५,००० लॅपटॉप अनुदान',
    heroHighlight2: 'IIT, IIM, AIIMS, NIT आणि राष्ट्रीय विधी विद्यापीठांसाठी',
    heroDesc2: 'प्रमुख संस्थांमध्ये शिकणाऱ्या एसटी विद्यार्थ्यांना १००% फी परतावा, ₹३६,००० वार्षिक निर्वाह भत्ता आणि ₹४५,००० लॅपटॉप अनुदान.',
    heroPrimary2: 'टॉप-क्लास अर्ज करा',
    heroSecondary2: '२४६ संस्थांची यादी',
    heroFeat2_1: '१००% पूर्ण फी परतावा',
    heroFeat2_2: '₹३६,००० निर्वाह भत्ता',
    heroFeat2_3: '₹४५,००० लॅपटॉप अनुदान',
    heroFeat2_4: 'दिव्यांग विशेष सहाय्य',
    heroStatVal2: '२४६ संस्था',
    heroStatLbl2: 'देशभरातील आघाडीच्या संस्था',

    heroBadge3: 'राष्ट्रीय परदेशी शिष्यवृत्ती (NOS)',
    heroTitle3: 'जगातील अव्वल ५०० QS विद्यापीठांमध्ये शिक्षण',
    heroHighlight3: 'पूर्ण परदेशी फी + $१५,४०० वार्षिक भत्ता',
    heroDesc3: 'मास्टर्स व पीएचडीसाठी विमान प्रवास, व्हिसा फी आणि आरोग्य विमा पूर्णपणे भारत सरकार देईल.',
    heroPrimary3: 'परदेशी शिष्यवृत्ती (NOS) अर्ज',
    heroSecondary3: 'फायदे तपासा',
    heroFeat3_1: 'अव्वल ५०० QS संस्था',
    heroFeat3_2: '$१५,४००/वर्ष (USA) • £९,९००/वर्ष (UK)',
    heroFeat3_3: 'येण्या-जाण्याचे विमान भाडे',
    heroFeat3_4: 'व्हिसा व आरोग्य विमा',
    heroStatVal3: '$१५,४००/वर्ष',
    heroStatLbl3: 'वार्षिक निर्वाह भत्ता अनुदान',

    heroBadge4: 'राष्ट्रीय फेलोशिप (NFST)',
    heroTitle4: 'एसटी संशोधकांसाठी डॉक्टरेट फेलोशिप',
    heroHighlight4: '₹३१,०००/महिना JRF • ₹३५,०००/महिना SRF + HRA',
    heroDesc4: 'यूजीसी मान्यताप्राप्त विद्यापीठांमध्ये एम.फिल आणि पीएचडीसाठी कोणत्याही कौटुंबिक उत्पन्नाच्या मर्यादेशिवाय गुणवत्ता फेलोशिप.',
    heroPrimary4: 'NFST फेलोशिप अर्ज',
    heroSecondary4: 'जागो AI ला विचारा',
    heroFeat4_1: 'उत्पन्नाची मर्यादा नाही',
    heroFeat4_2: '₹३१,००० - ₹३५,००० प्रति महिना',
    heroFeat4_3: 'वार्षिक आकस्मिक खर्च निधी',
    heroFeat4_4: 'PVTG विशेष कोटा',
    heroStatVal4: '₹३५,०००/महिना',
    heroStatLbl4: 'सिनियर रिसर्च फेलोशिप (SRF)',

    verifiedGovtScheme: 'प्रमाणित शासकीय योजना',
    appMode: 'अर्ज पद्धत',
    onlinePwa: '१००% ऑनलाइन (PWA)',
    disbChannel: 'वितरण माध्यम',
    directApbsDbt: 'थेट बँक खात्यात (DBT)',
    docVerif: 'कागदपत्र पडताळणी',
    digilockerPki: 'डिजीलॉकर e-KYC',
    slideOf: 'स्लाइड',

    loginTitle: 'सुरक्षित पोर्टल लॉगिन (E2EE)',
    loginSubtitle: 'आदिवासी कार्य मंत्रालय (MoTA) • भारत सरकार',
    loginBadgeOnePortal: 'सर्व ५ MoTA योजनांसाठी एकल सुरक्षित खिडकी',
    tabMobileOtp: 'विद्यार्थी मोबाईल OTP',
    tabApaarDigi: 'अपार (APAAR) / डिजीलॉकर',
    tabOfficerAishe: 'अधिकारी AISHE / नोडल',
    e2eeBadge: 'E2EE क्रिप्टोग्राफिक सत्र सक्रिय (TLS 1.3 • AES-256-GCM)',
    e2eeNotice: 'सर्व प्रमाणीकरण डेटा क्लायंट बाजूने सुरक्षित एन्क्रिप्ट केला जातो. DPDP कायदा २०२३ प्रमाणित.',
    mobileInputLabel: 'मोबाईल नंबर (आधार / DBT जोडलेला)',
    mobilePlaceholder: '१० अंकी मोबाईल नंबर टाका',
    enterOtpLabel: '६ अंकी सुरक्षित OTP टाका',
    otpSentNotice: 'एक सुरक्षित OTP यावर पाठवला आहे:',
    didNotReceiveOtp: 'OTP आला नाही का?',
    resendOtpIn: 'पुन्हा पाठवा:',
    resendOtpNow: 'आता OTP पाठवा',
    submitOtpVerify: 'सुरक्षितपणे लॉगिन करा',
    sendOtpBtn: 'सुरक्षित OTP मिळवा',
    useDevOtp: 'डेमो OTP वापरा',
    apaarInputLabel: '१२ अंकी APAAR / EduID नंबर',
    apaarPlaceholder: 'उदा. 1234-5678-9012',
    apaarAuthNotice: 'APAAR थेट शैक्षणिक बँक आणि डिजीलॉकरशी जोडलेले आहे.',
    apaarVerifyBtn: 'डिजीलॉकरद्वारे पडताळणी करा',
    aisheCodeLabel: 'संस्था AISHE कोड / आयडी',
    aishePlaceholder: 'उदा. U-0306 (IIT Bombay)',
    officerPasswordLabel: 'अधिकारी एन्क्रिप्शन पासवर्ड',
    securityPinLabel: '2FA ई-गव्हर्नन्स सुरक्षा पिन',
    officerLoginBtn: 'कन्सोल लॉगिन करा',
    orQuickDemoPersonas: 'किंवा १-क्लिक डेमो भूमिका निवडा',

    findScholarshipTitle: 'आपल्यासाठी योग्य शिष्यवृत्ती शोधा',
    findScholarshipSub: 'काही सेकंदात ५ MoTA योजना तपासा',
    aiAssistedTag: 'AI पात्रता तपासणी',
    eduLevelLabel: '१. शिक्षण स्तर',
    stateLabel: '२. राज्य / प्रदेश',
    tribalCatLabel: '३. आदिवासी प्रवर्ग',
    incomeLabel: '४. वार्षिक कौटुंबिक उत्पन्न',
    checkMatchedBtn: 'पात्र योजना तपासा',

    allowanceCalcTitle: 'शिष्यवृत्ती भत्ता व आर्थिक पात्रता कॅल्क्युलेटर',
    allowanceCalcDesc: 'पूर्ण फी, मासिक निर्वाह भत्ता आणि ₹४५,००० लॅपटॉप अनुदान मोजा.',
    totalEstAnnual: 'एकूण अंदाजे वार्षिक पात्रता',
    tuitionSupport: 'शिक्षण शुल्क सहाय्य',
    livingMaintenance: 'निर्वाह भत्ता',
    hardwareLaptop: 'लॅपटॉप अनुदान',
    proceedClaim: 'अर्ज करण्यासाठी पुढे जा',
    launchComparator: 'योजना तुलना टूल',

    stat1Val: '५',
    stat1Lbl: 'अधिकृत MoTA योजना',
    stat1Sub: 'एकल खिडकी मंच',
    stat2Val: '₹१,४२०+ कोटी',
    stat2Lbl: 'PFMS DBT वितरण',
    stat2Sub: 'थेट बँक खात्यात',
    stat3Val: '३८.५ लाख+',
    stat3Lbl: 'लाभार्थी आदिवासी विद्यार्थी',
    stat3Sub: '३६ राज्ये व केंद्रशासित प्रदेश',
    stat4Val: '२४६',
    stat4Lbl: 'प्रमुख संस्था',
    stat4Sub: 'IIT, IIM, AIIMS, NIT',
    stat5Val: '१००%',
    stat5Lbl: 'डिजीलॉकर सत्यापित',
    stat5Sub: 'पेपरलेस अर्ज',

    footerMinistry: 'आदिवासी कार्य मंत्रालय',
    footerGovt: 'भारत सरकार • Government of India',
    footerAbout: 'जनजाती सेतू (JanjatiSetu) - भारतातील अनुसूचित जमाती (ST) विद्यार्थ्यांसाठी एकल खिडकी शिष्यवृत्ती मंच. डिजीलॉकर व थेट बँक खात्यात PFMS DBT.',
    allRightsReserved: 'आदिवासी कार्य मंत्रालय, भारत सरकार. सर्व हक्क राखीव.'
  },

  sat: {
    siteName: 'ᱡᱟᱱᱡᱟᱛᱤ ᱥᱮᱛᱩ',
    siteNameRegional: 'JanjatiSetu',
    siteTagline: 'ᱡᱟᱱᱡᱟᱛᱤ ᱯᱟᱹᱴᱷᱩᱣᱟᱹ ᱠᱚᱣᱟᱜ ᱥᱠᱚᱞᱟᱨᱥᱤᱯ ᱯᱚᱨᱴᱟᱞ',
    ministryName: 'ᱡᱟᱱᱡᱟᱛᱤ ᱢᱚᱱᱛᱨᱟᱞᱚᱭ (MoTA)',
    govIndia: 'ᱵᱷᱟᱨᱚᱛ ᱥᱚᱨᱠᱟᱨ',
    dbtMissionCompliance: 'Direct Benefit Transfer (DBT) & DPDP Act 2023 Compliant',
    roleSwitcher: 'Role Switcher',
    demoPersonas: 'Demo Personas',
    demoSub: 'Test all 5 schemes',
    ninePersonas: '9 Personas',

    home: 'ᱚᱲᱟᱜ (Home)',
    schemes: 'ᱥᱠᱤᱢ ᱠᱚ (Schemes)',
    predictorsTools: 'ᱠᱟᱞᱠᱩᱞᱮᱴᱚᱨ (Tools)',
    wallet: 'DigiLocker Wallet',
    dbtTracker: 'PFMS DBT Tracker',
    grievance: 'ᱜᱩᱦᱟᱹᱨ (Grievance)',
    officerConsole: 'Officer Console',
    applyForFY: 'Apply for FY26-27',
    askJago: 'JAGO ᱠᱩᱞᱤᱭᱮᱢ',
    signIn: 'Sign In',
    signOut: 'Log Out',
    profile: 'Profile',
    searchPlaceholder: 'Search 5 MoTA schemes, DigiLocker, IITs...',
    matchingResults: 'Matching Results',

    heroBadge1: 'Academic Year 2026-27 Open',
    heroTitle1: 'ᱡᱟᱱᱡᱟᱛᱤ ᱥᱮᱛᱩ • Portal for ST Students',
    heroHighlight1: '38.5 Lakh+ ST Students Supported Across India',
    heroDesc1: 'Single-window scholarship discovery with 100% paperless DigiLocker e-KYC and direct bank transfer via PFMS.',
    heroPrimary1: '5 ᱜᱚᱴᱟᱝ ᱥᱠᱤᱢ ᱧᱮᱞᱢᱮ',
    heroSecondary1: 'DigiLocker Vault',
    heroFeat1_1: '100% Paperless DigiLocker',
    heroFeat1_2: 'Direct PFMS Bank Credit',
    heroFeat1_3: 'Zero Application Fee',
    heroFeat1_4: 'JAGO Voice AI',
    heroStatVal1: '₹1,420 Cr+',
    heroStatLbl1: 'Direct Benefit Transfer (DBT) via PFMS',

    heroBadge2: 'Top-Class Education • 246 Premier Institutes',
    heroTitle2: 'Full Tuition + ₹45,000 Laptop Grant',
    heroHighlight2: 'For IITs, IIMs, AIIMS & NITs',
    heroDesc2: 'Full tuition fee reimbursement + ₹36,000/yr living allowance + ₹45,000 laptop grant.',
    heroPrimary2: 'Apply Top-Class',
    heroSecondary2: '246 Institutes List',
    heroFeat2_1: '100% Full Fees',
    heroFeat2_2: '₹36,000 Living Grant',
    heroFeat2_3: '₹45,000 Laptop Grant',
    heroFeat2_4: 'Divyang Support',
    heroStatVal2: '246 Institutes',
    heroStatLbl2: 'Top Empanelled Colleges',

    heroBadge3: 'National Overseas Scholarship (NOS)',
    heroTitle3: 'Study at Top 500 QS World Universities',
    heroHighlight3: 'Full Foreign Tuition + USD 15,400 Allowance',
    heroDesc3: 'Full foreign tuition + living expenses + return airfare covered by MoTA.',
    heroPrimary3: 'Apply NOS Overseas',
    heroSecondary3: 'Compare Benefits',
    heroFeat3_1: 'Top 500 QS Universities',
    heroFeat3_2: '$15,400/yr Allowance',
    heroFeat3_3: 'Return Airfare Covered',
    heroFeat3_4: 'Visa & Health Insurance',
    heroStatVal3: '$15,400/yr',
    heroStatLbl3: 'Living Allowance',

    heroBadge4: 'National Fellowship (NFST)',
    heroTitle4: 'Doctoral Fellowship for ST Scholars',
    heroHighlight4: '₹31,000/mo JRF • ₹35,000/mo SRF + HRA',
    heroDesc4: 'M.Phil & Ph.D. research fellowship with zero family income ceiling.',
    heroPrimary4: 'Apply NFST Fellowship',
    heroSecondary4: 'Ask JAGO AI',
    heroFeat4_1: 'No Income Cap',
    heroFeat4_2: '₹31,000 - ₹35,000/month',
    heroFeat4_3: 'Contingency Grant',
    heroFeat4_4: 'PVTG Priority',
    heroStatVal4: '₹35,000/mo',
    heroStatLbl4: 'SRF Fellowship',

    verifiedGovtScheme: 'Verified Scheme',
    appMode: 'Application Mode',
    onlinePwa: '100% Online',
    disbChannel: 'Payment Channel',
    directApbsDbt: 'Direct APBS DBT',
    docVerif: 'Verification',
    digilockerPki: 'DigiLocker PKI',
    slideOf: 'Slide',

    loginTitle: 'Secure Portal Login (E2EE)',
    loginSubtitle: 'Ministry of Tribal Affairs • Government of India',
    loginBadgeOnePortal: 'Single Authorized Window for All 5 Schemes',
    tabMobileOtp: 'Student Mobile OTP',
    tabApaarDigi: 'APAAR / DigiLocker',
    tabOfficerAishe: 'Officer AISHE',
    e2eeBadge: 'E2EE Cryptographic Handshake Active (TLS 1.3 • AES-256-GCM)',
    e2eeNotice: 'All data encrypted client-side. DPDP Act 2023 Certified.',
    mobileInputLabel: 'Mobile Number (Aadhaar / DBT Linked)',
    mobilePlaceholder: 'Enter 10-digit mobile number',
    enterOtpLabel: 'Enter 6-Digit Secure OTP',
    otpSentNotice: 'OTP sent to:',
    didNotReceiveOtp: "Didn't receive OTP?",
    resendOtpIn: 'Resend in:',
    resendOtpNow: 'Resend OTP Now',
    submitOtpVerify: 'Authorize & Sign In',
    sendOtpBtn: 'Generate Secure OTP',
    useDevOtp: 'Use Instant Demo OTP',
    apaarInputLabel: '12-Digit APAAR / EduID',
    apaarPlaceholder: 'e.g. 1234-5678-9012',
    apaarAuthNotice: 'APAAR links directly with DigiLocker.',
    apaarVerifyBtn: 'Authenticate via DigiLocker',
    aisheCodeLabel: 'Institution AISHE Code',
    aishePlaceholder: 'e.g. U-0306 (IIT Bombay)',
    officerPasswordLabel: 'Officer Password',
    securityPinLabel: '2FA Security PIN',
    officerLoginBtn: 'Login to Console',
    orQuickDemoPersonas: 'Or 1-Click Demo Personas',

    findScholarshipTitle: 'ᱟᱢ ᱞᱟᱹᱜᱤᱫ ᱥᱠᱚᱞᱟᱨᱥᱤᱯ ᱥᱮᱸᱫᱽᱨᱟᱭ ᱢᱮ',
    findScholarshipSub: 'Check 5 MoTA Central Schemes in seconds',
    aiAssistedTag: 'AI Eligibility Check',
    eduLevelLabel: '1. Education Level',
    stateLabel: '2. State / Region',
    tribalCatLabel: '3. Tribal Category',
    incomeLabel: '4. Annual Income',
    checkMatchedBtn: 'Check Matched Schemes',

    allowanceCalcTitle: 'Scholarship Allowance Calculator',
    allowanceCalcDesc: 'Estimate tuition fees, living allowance and ₹45,000 laptop grant.',
    totalEstAnnual: 'Total Estimated Entitlement',
    tuitionSupport: 'Tuition Fee Support',
    livingMaintenance: 'Living Allowance',
    hardwareLaptop: '₹45,000 Laptop Grant',
    proceedClaim: 'Proceed with Claim',
    launchComparator: 'Scheme Comparator',

    stat1Val: '5',
    stat1Lbl: 'MoTA Schemes',
    stat1Sub: 'Single-Window',
    stat2Val: '₹1,420+ Cr',
    stat2Lbl: 'PFMS DBT Disbursed',
    stat2Sub: 'Direct to Bank',
    stat3Val: '38.5 Lakh+',
    stat3Lbl: 'ST Students Funded',
    stat3Sub: 'All India',
    stat4Val: '246',
    stat4Lbl: 'Premier Institutes',
    stat4Sub: 'IITs/IIMs',
    stat5Val: '100%',
    stat5Lbl: 'DigiLocker Verified',
    stat5Sub: 'Paperless',

    footerMinistry: 'Ministry of Tribal Affairs',
    footerGovt: 'Government of India',
    footerAbout: 'JanjatiSetu (ᱡᱟᱱᱡᱟᱛᱤ ᱥᱮᱛᱩ) - Unified Single-Window Scholarship Discovery & Disbursement Platform for ST students.',
    allRightsReserved: 'Ministry of Tribal Affairs, Government of India.'
  },

  gon: {
    siteName: 'जनजाति सेतु',
    siteNameRegional: 'JanjatiSetu',
    siteTagline: 'गोंडी छात्रवृत्ति पोर्टल',
    ministryName: 'जनजातीय कार्य मंत्रालय (MoTA)',
    govIndia: 'भारत सरकार',
    dbtMissionCompliance: 'DBT Mission & DPDP Act 2023 Compliant',
    roleSwitcher: 'भूमिका बदलो',
    demoPersonas: 'डेमो व्यक्तित्व',
    demoSub: '5 योजनाएं देखें',
    ninePersonas: '9 रोल',

    home: 'मुख्य (Home)',
    schemes: 'योजनाएं (Schemes)',
    predictorsTools: 'टूल्स (Tools)',
    wallet: 'डिजिलॉकर (Wallet)',
    dbtTracker: 'PFMS DBT',
    grievance: 'शिकायत (Help)',
    officerConsole: 'अधिकारी कंसोल',
    applyForFY: 'आवेदन करो (2026-27)',
    askJago: 'जागो से पूछो',
    signIn: 'लॉग इन',
    signOut: 'लॉग आउट',
    profile: 'प्रोफ़ाइल',
    searchPlaceholder: 'योजना, कॉलेज, डिजिलॉकर खोजो...',
    matchingResults: 'परिणाम',

    heroBadge1: 'सत्र 2026-27 खुला है',
    heroTitle1: 'जनजाति सेतु • गोंड व आदिवासी छात्रों का पोर्टल',
    heroHighlight1: 'भारत भर के 38.5 लाख+ आदिवासी छात्रों का विकास',
    heroDesc1: 'सभी 5 सरकारी छात्रवृत्ति योजनाओं में डिजिलॉकर से सीधे बैंक खाते में भुगतान।',
    heroPrimary1: 'योजनाएं देखें',
    heroSecondary1: 'डिजिलॉकर वॉल्ट',
    heroFeat1_1: '100% पेपरलेस डिजिलॉकर',
    heroFeat1_2: 'सीधा बैंक भुगतान (PFMS)',
    heroFeat1_3: 'फ्री आवेदन',
    heroFeat1_4: 'जागो (JAGO) AI',
    heroStatVal1: '₹1,420 करोड़+',
    heroStatLbl1: 'PFMS द्वारा सीधा बैंक भुगतान (DBT)',

    heroBadge2: 'शीर्ष कॉलेज • 246 प्रमुख संस्थान',
    heroTitle2: 'पूरी फीस + ₹45,000 लैपटॉप सहायता',
    heroHighlight2: 'IIT, IIM, AIIMS और NIT छात्रों के लिए',
    heroDesc2: 'पूरी कॉलेज फीस + ₹36,000 वार्षिक खर्च + ₹45,000 लैपटॉप सहायता।',
    heroPrimary2: 'टॉप-क्लास आवेदन',
    heroSecondary2: '246 कॉलेज सूची',
    heroFeat2_1: '100% पूरी फीस वापसी',
    heroFeat2_2: '₹36,000 रहने का खर्च',
    heroFeat2_3: '₹45,000 लैपटॉप अनुदान',
    heroFeat2_4: 'दिव्यांग सहायता',
    heroStatVal2: '246 कॉलेज',
    heroStatLbl2: 'प्रमुख सरकारी संस्थान',

    heroBadge3: 'विदेश छात्रवृत्ति (NOS)',
    heroTitle3: 'दुनिया के टॉप 500 यूनिवर्सिटी में पढ़ाई',
    heroHighlight3: 'पूरी फीस + $15,400 सालाना खर्च',
    heroDesc3: 'विदेश में पढ़ाई के लिए हवाई टिकट, वीजा और फीस भारत सरकार द्वारा।',
    heroPrimary3: 'विदेश छात्रवृत्ति आवेदन',
    heroSecondary3: 'तुलना करें',
    heroFeat3_1: 'टॉप 500 QS कॉलेज',
    heroFeat3_2: '$15,400/साल खर्च',
    heroFeat3_3: 'हवाई टिकट शामिल',
    heroFeat3_4: 'वीजा व बीमा',
    heroStatVal3: '$15,400/साल',
    heroStatLbl3: 'सालाना खर्च सहायता',

    heroBadge4: 'राष्ट्रीय फैलोशिप (NFST)',
    heroTitle4: 'आदिवासी शोधार्थियों के लिए फैलोशिप',
    heroHighlight4: '₹31,000/माह JRF • ₹35,000/माह SRF + HRA',
    heroDesc4: 'एम.फिल व पीएचडी के लिए बिना किसी आय सीमा के योग्यता फैलोशिप।',
    heroPrimary4: 'NFST आवेदन',
    heroSecondary4: 'जागो AI',
    heroFeat4_1: 'आय सीमा नहीं',
    heroFeat4_2: '₹31,000 - ₹35,000/माह',
    heroFeat4_3: 'आकस्मिक खर्च अनुदान',
    heroFeat4_4: 'PVTG विशेष कोटा',
    heroStatVal4: '₹35,000/माह',
    heroStatLbl4: 'SRF फैलोशिप',

    verifiedGovtScheme: 'सत्यापित योजना',
    appMode: 'आवेदन माध्यम',
    onlinePwa: '100% ऑनलाइन',
    disbChannel: 'भुगतान माध्यम',
    directApbsDbt: 'सीधा बैंक खाता (DBT)',
    docVerif: 'कागजात जांच',
    digilockerPki: 'डिजिलॉकर ई-केवाईसी',
    slideOf: 'स्लाइड',

    loginTitle: 'सुरक्षित पोर्टल लॉगिन (E2EE)',
    loginSubtitle: 'जनजातीय कार्य मंत्रालय • भारत सरकार',
    loginBadgeOnePortal: 'सभी 5 योजनाओं के लिए एक सुरक्षित मंच',
    tabMobileOtp: 'मोबाइल OTP',
    tabApaarDigi: 'अपार / डिजिलॉकर',
    tabOfficerAishe: 'अधिकारी AISHE',
    e2eeBadge: 'सुरक्षित E2EE एन्क्रिप्शन सक्रिय (TLS 1.3 • AES-256-GCM)',
    e2eeNotice: 'सभी डेटा सुरक्षित एन्क्रिप्शन के साथ भेजा जाता है। DPDP Act 2023.',
    mobileInputLabel: 'मोबाइल नंबर (आधार से लिंक)',
    mobilePlaceholder: '10 अंकों का मोबाइल नंबर',
    enterOtpLabel: '6 अंकों का OTP दर्ज करें',
    otpSentNotice: 'सुरक्षित OTP भेजा गया:',
    didNotReceiveOtp: 'OTP नहीं मिला?',
    resendOtpIn: 'पुनः भेजें:',
    resendOtpNow: 'अभी OTP भेजें',
    submitOtpVerify: 'सत्यापित करें और लॉगिन करें',
    sendOtpBtn: 'OTP भेजें',
    useDevOtp: 'डेमो OTP भरें',
    apaarInputLabel: '12 अंकों का APAAR नंबर',
    apaarPlaceholder: 'उदा. 1234-5678-9012',
    apaarAuthNotice: 'APAAR सीधे डिजिलॉकर से जुड़ता है।',
    apaarVerifyBtn: 'डिजिलॉकर से लॉगिन करें',
    aisheCodeLabel: 'कॉलेज AISHE कोड',
    aishePlaceholder: 'उदा. U-0306',
    officerPasswordLabel: 'पासवर्ड',
    securityPinLabel: 'सुरक्षा पिन (PIN)',
    officerLoginBtn: 'अधिकारी लॉगिन',
    orQuickDemoPersonas: 'या 1-क्लिक डेमो चुनें',

    findScholarshipTitle: 'अपनी छात्रवृत्ति खोजो',
    findScholarshipSub: 'सेकंडों में 5 योजनाएं जांचें',
    aiAssistedTag: 'AI पात्रता जांच',
    eduLevelLabel: '1. पढ़ाई का स्तर',
    stateLabel: '2. राज्य / क्षेत्र',
    tribalCatLabel: '3. जनजातीय समूह',
    incomeLabel: '4. वार्षिक आय',
    checkMatchedBtn: 'पात्र योजना जांचें',

    allowanceCalcTitle: 'छात्रवृत्ति भत्ता कैलकुलेटर',
    allowanceCalcDesc: 'फीस, मासिक खर्च और ₹45,000 लैपटॉप सहायता की गणना करें।',
    totalEstAnnual: 'कुल वार्षिक राशि',
    tuitionSupport: 'फीस सहायता',
    livingMaintenance: 'मासिक खर्च',
    hardwareLaptop: 'लैपटॉप अनुदान',
    proceedClaim: 'आवेदन करो',
    launchComparator: 'योजना तुलना',

    stat1Val: '5',
    stat1Lbl: 'MoTA योजनाएं',
    stat1Sub: 'एकल खिड़की',
    stat2Val: '₹1,420+ करोड़',
    stat2Lbl: 'PFMS DBT भुगतान',
    stat2Sub: 'सीधे बैंक खाते में',
    stat3Val: '38.5 लाख+',
    stat3Lbl: 'आदिवासी छात्र',
    stat3Sub: 'पूरे भारत में',
    stat4Val: '246',
    stat4Lbl: 'प्रमुख कॉलेज',
    stat4Sub: 'IIT, IIM, AIIMS',
    stat5Val: '100%',
    stat5Lbl: 'डिजिलॉकर सत्यापित',
    stat5Sub: 'पेपरलेस',

    footerMinistry: 'जनजातीय कार्य मंत्रालय',
    footerGovt: 'भारत सरकार',
    footerAbout: 'जनजाति सेतु - आदिवासी छात्रों के लिए एकल छात्रवृत्ति मंच। डिजिलॉकर और PFMS सीधा भुगतान।',
    allRightsReserved: 'जनजातीय कार्य मंत्रालय, भारत सरकार।'
  },

  te: {
    siteName: 'జనజాతి సేతు',
    siteNameRegional: 'JanjatiSetu',
    siteTagline: 'ఏకీకృత గిరిజన స్కాలర్‌షిప్ పోర్టల్',
    ministryName: 'గిరిజన వ్యవహారాల మంత్రిత్వ శాఖ (MoTA)',
    govIndia: 'భారత ప్రభుత్వం',
    dbtMissionCompliance: 'డైరెక్ట్ బెనిఫిట్ ట్రాన్స్‌ఫర్ (DBT) & DPDP చట్టం 2023 అనుకూలం',
    roleSwitcher: 'ప్రొఫైల్ మార్చు',
    demoPersonas: '1-క్లిక్ డెమో ప్రొఫైల్స్',
    demoSub: 'అన్ని 5 పథకాలు పరిశీలించండి',
    ninePersonas: '9 ప్రొఫైల్స్',

    home: 'హోమ్',
    schemes: 'స్కాలర్‌షిప్ పథకాలు',
    predictorsTools: 'క్యాలిక్యులేటర్ & టూల్స్',
    wallet: 'డిజిలాకర్ వాలెట్',
    dbtTracker: 'PFMS DBT ట్రాకర్',
    grievance: 'ఫిర్యాదు & అప్పీల్',
    officerConsole: 'అధికారి కన్సోల్',
    applyForFY: '2026-27 కోసం దరఖాస్తు చేయండి',
    askJago: 'జాగో ని అడగండి',
    signIn: 'సైన్ ఇన్',
    signOut: 'లాగ్ అవుట్',
    profile: 'ప్రొఫైల్',
    searchPlaceholder: 'MoTA పథకాలు, IITs/IIMs, డిజిలాకర్ శోధించండి...',
    matchingResults: 'సరిపోలిన ఫలితాలు',

    heroBadge1: 'విద్యా సంవత్సరం 2026-27 దరఖాస్తులు ప్రారంభం',
    heroTitle1: 'జనజాతి సేతు • గిరిజన విద్యార్థుల ఏకీకృత పోర్టల్',
    heroHighlight1: 'భారతదేశం అంతటా 38.5 లక్షల+ ST విద్యార్థులకు సాధికారత',
    heroDesc1: 'డిజిలాకర్ ఇ-కెవైసితో అన్ని 5 గిరిజన మంత్రిత్వ శాఖ స్కాలర్‌షిప్‌లకు కాగిత రహిత దరఖాస్తు.',
    heroPrimary1: '5 పథకాలను చూడండి',
    heroSecondary1: 'డిజిలాకర్ వాల్ట్',
    heroFeat1_1: '100% కాగిత రహిత డిజిలాకర్',
    heroFeat1_2: 'PFMS ద్వారా బ్యాంక్ ఖాతాకు జమ',
    heroFeat1_3: 'ఉచిత దరఖాస్తు',
    heroFeat1_4: 'బహుభాషా జాగో (JAGO) AI',
    heroStatVal1: '₹1,420 కోట్లు+',
    heroStatLbl1: 'PFMS ద్వారా నేరుగా బ్యాంక్ ఖాతాకు (DBT)',

    heroBadge2: 'టాప్ క్లాస్ ఉన్నత విద్య • 246 ప్రముఖ సంస్థలు',
    heroTitle2: 'పూర్తి ఫీజు + ₹45,000 ల్యాప్‌టాప్ గ్రాంట్',
    heroHighlight2: 'IIT, IIM, AIIMS, NIT విద్యార్థుల కోసం',
    heroDesc2: '100% ఫీజు రీయింబర్స్‌మెంట్, ₹36,000 వార్షిక జీవన భత్యం మరియు ₹45,000 ల్యాప్‌టాప్ సహాయం.',
    heroPrimary2: 'టాప్-క్లాస్ దరఖాస్తు చేయండి',
    heroSecondary2: '246 విద్యా సంస్థల జాబితా',
    heroFeat2_1: '100% పూర్తి ఫీజు రీయింబర్స్‌మెంట్',
    heroFeat2_2: '₹36,000 వార్షిక జీవన భత్యం',
    heroFeat2_3: '₹45,000 ల్యాప్‌టాప్ గ్రాంట్',
    heroFeat2_4: 'దివ్యాంగుల సహాయం',
    heroStatVal2: '246 విద్యా సంస్థలు',
    heroStatLbl2: 'దేశవ్యాప్తంగా ప్రముఖ విద్యా సంస్థలు',

    heroBadge3: 'నేషనల్ ఓవర్సీస్ స్కాలర్‌షిప్ (NOS)',
    heroTitle3: 'ప్రపంచంలోని టాప్ 500 QS వర్సిటీలలో విద్య',
    heroHighlight3: 'పూర్తి విదేశీ ఫీజు + $15,400 వార్షిక భత్యం',
    heroDesc3: 'విదేశాల్లో మాస్టర్స్ & పీహెచ్‌డీ కోసం విమాన ఛార్జీలు, వీసా ఫీజులు మరియు భత్యం ప్రభుత్వం భరిస్తుంది.',
    heroPrimary3: 'విదేశీ విద్య (NOS) దరఖాస్తు',
    heroSecondary3: 'ప్రయోజనాలను పోల్చండి',
    heroFeat3_1: 'టాప్ 500 QS వర్సిటీలు',
    heroFeat3_2: '$15,400/సం. (USA) • £9,900/సం. (UK)',
    heroFeat3_3: 'రాను-పోను విమాన ఛార్జీలు',
    heroFeat3_4: 'వీసా & ఆరోగ్య బీమా',
    heroStatVal3: '$15,400/సం.',
    heroStatLbl3: 'వార్షిక జీవన భత్యం',

    heroBadge4: 'నేషనల్ ఫెలోషిప్ (NFST)',
    heroTitle4: 'ఎస్టీ పరిశోధకులకు డాక్టోరల్ ఫెలోషిప్',
    heroHighlight4: '₹31,000/నెల JRF • ₹35,000/నెల SRF + HRA',
    heroDesc4: 'యూజీసీ గుర్తింపు పొందిన వర్సిటీలలో ఎం.ఫిల్ మరియు పీహెచ్‌డీ విద్యార్థులకు ఎలాంటి ఆదాయ పరిమితి లేని ఫెలోషిప్.',
    heroPrimary4: 'NFST ఫెలోషిప్ దరఖాస్తు',
    heroSecondary4: 'జాగో AI ని అడగండి',
    heroFeat4_1: 'కుటుంబ ఆదాయ పరిమితి లేదు',
    heroFeat4_2: '₹31,000 - ₹35,000 ప్రతి నెలా',
    heroFeat4_3: 'వార్షిక ఆకస్మిక గ్రాంట్',
    heroFeat4_4: 'PVTG ప్రత్యేక ప్రాధాన్యత కోటా',
    heroStatVal4: '₹35,000/నెల',
    heroStatLbl4: 'సీనియర్ రీసెర్చ్ ఫెలోషిప్ (SRF)',

    verifiedGovtScheme: 'ధృవీకరించబడిన ప్రభుత్వ పథకం',
    appMode: 'దరఖాస్తు విధానం',
    onlinePwa: '100% ఆన్‌లైన్ (PWA)',
    disbChannel: 'చెల్లింపు ఛానెల్',
    directApbsDbt: 'నేరుగా బ్యాంక్ ఖాతాకు (DBT)',
    docVerif: 'పత్రాల ధృవీకరణ',
    digilockerPki: 'డిజిలాకర్ e-KYC',
    slideOf: 'స్లైడ్',

    loginTitle: 'సురక్షిత పోర్టల్ లాగిన్ (E2EE)',
    loginSubtitle: 'గిరిజన వ్యవహారాల మంత్రిత్వ శాఖ • భారత ప్రభుత్వం',
    loginBadgeOnePortal: 'అన్ని 5 MoTA పథకాలకు ఏకీకృత సురక్షిత వేదిక',
    tabMobileOtp: 'విద్యార్థి మొబైల్ OTP',
    tabApaarDigi: 'అపార్ (APAAR) / డిజిలాకర్',
    tabOfficerAishe: 'అధికారి AISHE / అడ్మిన్',
    e2eeBadge: 'E2EE క్రిప్టోగ్రాఫిక్ సెషన్ సక్రియంగా ఉంది (TLS 1.3 • AES-256-GCM)',
    e2eeNotice: 'అన్ని లాగిన్ వివరాలు క్లయింట్ సైడ్ ఎన్‌క్రిప్ట్ చేయబడతాయి. DPDP చట్టం 2023 సర్టిఫైడ్.',
    mobileInputLabel: 'మొబైల్ నంబర్ (ఆధార్ / DBT లింక్ చేయబడినది)',
    mobilePlaceholder: '10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి',
    enterOtpLabel: '6 అంకెల సురక్షిత OTP నమోదు చేయండి',
    otpSentNotice: 'సురక్షిత OTP పంపబడింది:',
    didNotReceiveOtp: 'OTP రాలేదా?',
    resendOtpIn: 'మళ్ళీ పంపు:',
    resendOtpNow: 'ఇప్పుడే OTP పంపండి',
    submitOtpVerify: 'సురక్షితంగా లాగిన్ అవ్వండి',
    sendOtpBtn: 'సురక్షిత OTP పొందండి',
    useDevOtp: 'డెమో OTP ఉపయోగించండి',
    apaarInputLabel: '12 అంకెల APAAR / EduID నంబర్',
    apaarPlaceholder: 'ఉదా. 1234-5678-9012',
    apaarAuthNotice: 'APAAR నేరుగా డిజిలాకర్ మరియు అకడమిక్ బ్యాంక్‌తో లింక్ చేయబడింది.',
    apaarVerifyBtn: 'డిజిలాకర్ ద్వారా ప్రామాణీకరించండి',
    aisheCodeLabel: 'సంస్థ AISHE కోడ్ / ID',
    aishePlaceholder: 'ఉదా. U-0306 (IIT Bombay)',
    officerPasswordLabel: 'అధికారి ఎన్‌క్రిప్షన్ పాస్‌వర్డ్',
    securityPinLabel: '2FA ఈ-గవర్నెన్స్ సెక్యూరిటీ పిన్',
    officerLoginBtn: 'సమీక్ష కన్సోల్ లాగిన్',
    orQuickDemoPersonas: 'లేదా 1-క్లిక్ డెమో ప్రొఫైల్స్ ఎంచుకోండి',

    findScholarshipTitle: 'మీ కోసం తగిన స్కాలర్‌షిప్ పథకాలను కనుగొనండి',
    findScholarshipSub: 'క్షణాల్లో 5 MoTA పథకాలను తనిఖీ చేయండి',
    aiAssistedTag: 'AI అర్హత తనిఖీ',
    eduLevelLabel: '1. విద్యా స్థాయి',
    stateLabel: '2. రాష్ట్రం / ప్రాంతం',
    tribalCatLabel: '3. గిరిజన వర్గం',
    incomeLabel: '4. వార్షిక కుటుంబ ఆదాయం',
    checkMatchedBtn: 'అర్హత ఉన్న పథకాలను తనిఖీ చేయండి',

    allowanceCalcTitle: 'స్కాలర్‌షిప్ అలవెన్స్ & అర్హత క్యాలిక్యులేటర్',
    allowanceCalcDesc: 'ట్యూషన్ ఫీజు రీయింబర్స్‌మెంట్, నెలవారీ ఖర్చులు మరియు ₹45,000 ల్యాప్‌టాప్ గ్రాంట్‌ను లెక్కించండి.',
    totalEstAnnual: 'మొత్తం అంచనా వార్షిక అర్హత',
    tuitionSupport: 'ట్యూషన్ ఫీజు మద్దతు',
    livingMaintenance: 'నెలవారీ జీవన భత్యం',
    hardwareLaptop: 'ల్యాప్‌టాప్ గ్రాంట్',
    proceedClaim: 'దరఖాస్తుకు వెళ్లండి',
    launchComparator: 'పథకాల పోలిక సాధనం',

    stat1Val: '5',
    stat1Lbl: 'MoTA అధికారిక పథకాలు',
    stat1Sub: 'సింగిల్ విండో వేదిక',
    stat2Val: '₹1,420+ కోట్లు',
    stat2Lbl: 'PFMS DBT ద్వారా చెల్లింపు',
    stat2Sub: 'నేరుగా బ్యాంక్ ఖాతాకు',
    stat3Val: '38.5 లక్షలు+',
    stat3Lbl: 'లబ్ధి పొందిన గిరిజన విద్యార్థులు',
    stat3Sub: '36 రాష్ట్రాలు & కేంద్రపాలిత ప్రాంతాలు',
    stat4Val: '246',
    stat4Lbl: 'ప్రఖ్యాత విద్యా సంస్థలు',
    stat4Sub: 'IIT, IIM, AIIMS, NIT',
    stat5Val: '100%',
    stat5Lbl: 'డిజిలాకర్ ధృవీకరించబడింది',
    stat5Sub: 'కాగిత రహితం',

    footerMinistry: 'గిరిజన వ్యవహారాల మంత్రిత్వ శాఖ',
    footerGovt: 'భారత ప్రభుత్వం • Government of India',
    footerAbout: 'జనజాతి సేతు (JanjatiSetu) - గిరిజన విద్యార్థుల కోసం సింగిల్-విండో స్కాలర్‌షిప్ పోర్టల్. డిజిలాకర్ మరియు PFMS ప్రత్యక్ష బ్యాంక్ బదిలీ.',
    allRightsReserved: 'గిరిజన వ్యవహారాల మంత్రిత్వ శాఖ, భారత ప్రభుత్వం. సర్వ హక్కులు ప్రత్యేకించబడ్డాయి.'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    return localStorage.getItem('janjatisetu_lang') || localStorage.getItem('mota_app_lang') || 'en';
  });

  const setLanguage = (langCode) => {
    if (TRANSLATIONS[langCode]) {
      setCurrentLanguage(langCode);
      localStorage.setItem('janjatisetu_lang', langCode);
      localStorage.setItem('mota_app_lang', langCode);
      document.documentElement.lang = langCode;
    }
  };

  useEffect(() => {
    document.documentElement.lang = currentLanguage;
  }, [currentLanguage]);

  const t = (key, fallback = '') => {
    const langDict = TRANSLATIONS[currentLanguage] || TRANSLATIONS.en;
    if (langDict && langDict[key] !== undefined) {
      return langDict[key];
    }
    if (TRANSLATIONS.en && TRANSLATIONS.en[key] !== undefined) {
      return TRANSLATIONS.en[key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
