const fs = require('fs');
const path = require('path');

const TRANSLATIONS = {
  en: {
    // Brand & System
    siteName: 'JanjatiSetu',
    siteNameRegional: 'JanjatiSetu',
    siteTagline: 'Unified Tribal Scholarship Portal',
    ministryName: 'Ministry of Tribal Affairs (MoTA)',
    govIndia: 'Government of India',
    dbtMissionCompliance: 'Direct Benefit Transfer (DBT) Mission & DPDP Act 2023 Compliant',
    roleSwitcher: 'Role Switcher',
    demoPersonas: '1-Click Demo Personas',
    demoSub: 'Test all 5 schemes & officer consoles',
    ninePersonas: '9 Personas',

    // Navigation & Mega Menu
    home: 'Home',
    schemes: 'Scholarship Schemes',
    predictorsTools: 'Predictors & Tools',
    wallet: 'DigiLocker Wallet',
    dbtTracker: 'PFMS DBT Tracker',
    grievance: 'Grievance & Appeals',
    officerConsole: 'Officer Console',
    applyForFY: 'Apply for FY26-27',
    askJago: 'Ask JAGO',
    signIn: 'Sign In',
    signOut: 'Log Out',
    profile: 'Profile',
    searchPlaceholder: 'Search 5 MoTA schemes, 246 IITs/IIMs, DigiLocker, PFMS DBT...',
    matchingResults: 'Matching Results',
    cantFindAskJago: "Can't find what you need? Ask JAGO Multilingual AI",

    // Mega menu dropdowns
    schoolHigherEd: 'School & Higher Education',
    fellowshipsAbroad: 'Fellowships & Global Studies',
    allowanceCalculator: 'Allowance Calculator',
    allowanceCalcSub: 'Calculate financial entitlement based on fee & hosteller status',
    schemeComparator: 'Scheme Comparator',
    schemeComparatorSub: 'Compare 2-3 MoTA scholarships side-by-side',
    digilockerVault: 'DigiLocker Vault',
    digilockerVaultSub: 'Zero-upload digital document verification',
    pfmsLedger: 'PFMS DBT Ledger',
    pfmsLedgerSub: 'Live Aadhaar APBS bank credit status',
    viewAllSchemesMatrix: 'View All 5 Schemes Matrix',

    // Hero Section
    heroBadge1: 'Academic Year 2026-27 Open',
    heroTitle1: 'JanjatiSetu • Unified Portal for Tribal Students',
    heroHighlight1: 'Empowering 38.5 Lakh+ ST Scholars Across India',
    heroDesc1: 'Single-window discovery and paperless application for all 5 official Ministry of Tribal Affairs (MoTA) schemes with instant DigiLocker e-KYC and conflict-free processing.',
    heroPrimary1: 'Explore 5 MoTA Schemes',
    heroSecondary1: 'DigiLocker Vault',
    heroFeat1_1: '100% Paperless DigiLocker',
    heroFeat1_2: 'Real-time PFMS DBT',
    heroFeat1_3: 'Zero Application Fee',
    heroFeat1_4: 'Multi-lingual JAGO AI',
    heroStatVal1: '₹1,420 Cr+',
    heroStatLbl1: 'Direct Benefit Transfer (DBT) via PFMS',

    heroBadge2: 'Top-Class Education • 246 Premier Institutes',
    heroTitle2: 'Full Tuition + ₹45,000 Laptop Grant',
    heroHighlight2: 'For IITs, IIMs, AIIMS, NITs & National Law Universities',
    heroDesc2: 'ST students admitted into notified premier institutes receive full tuition fee reimbursement, ₹36,000/yr living expenses, ₹5,000 book grant and a one-time ₹45,000 laptop entitlement.',
    heroPrimary2: 'Apply Top-Class Scheme',
    heroSecondary2: 'Check 246 Institutes',
    heroFeat2_1: '100% Non-Refundable Fees',
    heroFeat2_2: '₹36,000 Living Expenses',
    heroFeat2_3: '₹45,000 Laptop Grant',
    heroFeat2_4: 'Divyang Assistance',
    heroStatVal2: '246 Institutes',
    heroStatLbl2: 'Empanelled Premier Institutes across India',

    heroBadge3: 'National Overseas Scholarship (NOS)',
    heroTitle3: 'Study at Top 500 QS World Universities',
    heroHighlight3: 'Full Foreign Tuition + USD 15,400 Annual Allowance',
    heroDesc3: 'Pursue Master’s and Ph.D. degrees in premier universities abroad with airfare, medical insurance, visa fees, contingency grants and living allowances funded by MoTA.',
    heroPrimary3: 'Apply Overseas (NOS)',
    heroSecondary3: 'Compare Benefits',
    heroFeat3_1: 'Top 500 QS Universities',
    heroFeat3_2: '$15,400/yr (USA) • £9,900/yr (UK)',
    heroFeat3_3: 'Return Airfare Covered',
    heroFeat3_4: 'Full Visa & Health Cover',
    heroStatVal3: '$15,400/yr',
    heroStatLbl3: 'Annual Living Maintenance Allowance',

    heroBadge4: 'National Fellowship for ST Students (NFST)',
    heroTitle4: 'Doctoral Fellowship for ST Scholars',
    heroHighlight4: '₹31,000/mo JRF • ₹35,000/mo SRF + HRA & Contingency',
    heroDesc4: 'Merit-based financial assistance for Scheduled Tribe students pursuing regular M.Phil and Ph.D. research courses in UGC-recognized Indian Universities with zero income cap.',
    heroPrimary4: 'Apply NFST Fellowship',
    heroSecondary4: 'Ask JAGO AI',
    heroFeat4_1: 'No Family Income Ceiling',
    heroFeat4_2: '₹31,000 - ₹35,000/month',
    heroFeat4_3: 'Annual Contingency Grant',
    heroFeat4_4: 'PVTG Priority Quota',
    heroStatVal4: '₹35,000/mo',
    heroStatLbl4: 'Senior Research Fellowship (SRF)',

    verifiedGovtScheme: 'Verified Govt Scheme',
    appMode: 'Application Mode',
    onlinePwa: '100% Online (PWA)',
    disbChannel: 'Disbursement Channel',
    directApbsDbt: 'Direct APBS Bank DBT',
    docVerif: 'Doc Verification',
    digilockerPki: 'DigiLocker PKI e-KYC',
    slideOf: 'Slide',
    ofTotal: 'of',
    heroDeadline: 'Deadline: Oct 31, 2026',
    pfmsSanctionsActive: 'PFMS Sanctions Active',

    // Scheme Finder Widget
    findScholarshipTitle: 'Find Scholarship Schemes For You',
    findScholarshipSub: 'Filter across 5 MoTA Central Schemes in seconds • 100% Conflict-Free Matching',
    aiAssistedTag: 'AI-Assisted Eligibility Check',
    eduLevelLabel: '1. Education Level',
    stateLabel: '2. State / Region',
    tribalCatLabel: '3. Tribal Category & Special Group',
    incomeLabel: '4. Annual Family Income',
    checkMatchedBtn: 'Check Matched Schemes & Entitlement',
    quickFilters: 'Quick Filters:',

    // How It Works
    howItWorksBadge: 'Simple 3-Step Process',
    howItWorksTitle: 'How Tribal Students Get Funded',
    howItWorksSub: 'From digital document fetch to direct bank transfer — a streamlined, transparent journey designed for ST scholars and families.',
    step1Title: 'Profile & DigiLocker e-KYC',
    step1Sub: 'Zero Physical Paperwork',
    step1Desc: 'Link your Aadhaar securely via DigiLocker. The portal automatically pulls and cryptographically validates your ST Tribe Certificate, Family Income, and 10th/12th Marksheets from State e-District databases.',
    step1Action: 'Open DigiLocker Vault',
    step2Title: 'AI Scheme Match & Conflict Check',
    step2Sub: 'Statutory 1-Scheme Enforcement',
    step2Desc: 'Our eligibility engine verifies your AISHE institution, degree level, and income threshold. The real-time conflict prevention engine guarantees you never face duplicate claim rejections.',
    step2Action: 'Check 5 MoTA Schemes',
    step3Title: '1-Click Apply & PFMS Direct DBT',
    step3Sub: 'Aadhaar-Seeded Bank Credit',
    step3Desc: 'Submit in under 2 minutes. Institutional and State Nodal Officers process applications with non-blocking timelines. Once sanctioned, funds transfer directly to your bank account via PFMS.',
    step3Action: 'Track PFMS DBT Status',
    dpdpGuarTitle: 'Statutory Data Privacy & Non-Blocking Verification',
    dpdpGuarDesc: '12-digit Aadhaar numbers are never stored in plain text. Verification adapter timeouts never block student application submission.',

    // Discovery Categories
    browseByCohortBadge: 'Direct Scheme Discovery',
    browseByCohortTitle: 'Browse MoTA Scholarships by Cohort',
    browseByCohortDesc: 'Select your educational level to view tailored benefits, statutory eligibility, and application forms.',
    viewAllMatrixBtn: 'View All Schemes Matrix',
    applyNow: 'Apply Now',
    trendingTools: 'Trending Tools & Predictors:',

    // Data & Tools (Calculator)
    interactiveToolsBadge: 'Interactive Tools & Predictors',
    allowanceCalcTitle: 'Scholarship Allowance & Entitlement Calculator',
    allowanceCalcDesc: 'Estimate your total financial entitlement — including tuition reimbursement, monthly living allowance, book grants, and one-time ₹45,000 laptop aid.',
    financialSimulator: 'Financial Entitlement Simulator',
    financialSimSub: 'Real-time calculation as per MoTA financial rules',
    selectSchemeLabel: 'Select Scholarship Scheme',
    annualTuitionLabel: 'Annual Compulsory Course / Tuition Fee',
    hostellerOption: 'Hosteller (Living Away)',
    divyangOption: 'Divyang (40%+ Disability)',
    laptopOption: '₹45,000 Laptop Grant',
    totalEstAnnual: 'Total Estimated Annual Entitlement',
    tuitionSupport: 'Tuition Support',
    livingMaintenance: 'Living / Maintenance',
    bookStationery: 'Book & Stationery',
    hardwareLaptop: 'Hardware / Laptop',
    proceedClaim: 'Proceed with Claim',
    launchComparator: 'Launch Scheme Comparator',
    openDigitalWallet: 'Open Digital Wallet',

    // Trust / Stats Bar
    stat1Val: '5',
    stat1Lbl: 'Official MoTA Schemes',
    stat1Sub: 'Single-Window Discovery',
    stat2Val: '₹1,420+ Cr',
    stat2Lbl: 'Disbursed via PFMS DBT',
    stat2Sub: 'Direct to Bank Account',
    stat3Val: '38.5 Lakh+',
    stat3Lbl: 'Tribal Scholars Funded',
    stat3Sub: 'Across 36 States & UTs',
    stat4Val: '246',
    stat4Lbl: 'Premier Institutes',
    stat4Sub: 'IITs, IIMs, AIIMS, NITs',
    stat5Val: '100%',
    stat5Lbl: 'DigiLocker Verified',
    stat5Sub: 'Zero Manual Paper Upload',

    // News & Updates
    officialNoticesBadge: 'Official Notifications',
    latestNewsTitle: 'Latest News, Sanction Orders & Circulars',
    latestNewsDesc: 'Real-time administrative notices, PFMS DBT sanction ledgers, and deadline alerts directly from Shastri Bhawan, New Delhi.',
    liveTickerTag: 'LIVE TICKER',
    liveTickerText: '🔥 Fresh applications for Academic Year 2026-27 are now active on JanjatiSetu • DigiLocker e-KYC is mandatory for zero-document upload.',
    allNotices: 'All Notices',
    sanctionsDbt: 'Sanctions & DBT',
    deadlines: 'Deadlines',
    guidelines: 'Guidelines',
    viewNotice: 'View Notice',
    downloadPdf: 'Download PDF',
    searchAllSanctions: 'Search All Central Sanctions in PFMS Ledger',

    // Expert Help & Community
    assistanceBadge: 'Assistance & Community',
    expertHelpTitle: 'Expert Help & Student Discussion Forum',
    expertHelpDesc: 'Get instant answers in your native language through the JAGO AI Voice Assistant or connect directly with MoTA Nodal Officers and tribal peer scholars.',
    jagoCardTitle: 'JAGO (जागो) Tribal AI Assistant',
    jagoCardDesc: 'Ask questions via Speech-to-Text or chat in 8 Indian languages with tribal cultural greetings (Johar!).',
    launchVoiceAssistant: 'Launch Voice Assistant Now',
    nationalHelpdesk: 'National Tribal Helpdesk',
    tollFreeHotline: 'Toll-Free National Hotline',
    monSatTiming: 'Mon-Sat (9 AM - 6 PM)',
    directGrievanceDesk: 'Direct Grievance Desk',
    fileAppeal: 'File Appeal',
    recentAnswersTitle: 'Recent Verified Expert Responses',
    askQuestionBtn: 'Ask a Question',
    askModalTitle: 'Ask MoTA Nodal Officers & Community',
    askModalDesc: 'Submit questions regarding eligibility, DigiLocker certificates or PFMS bank credits.',
    submitQuery: 'Submit Inquiry',

    // FAQ Accordion
    faqBadge: 'Frequently Asked Questions',
    faqTitle: 'Frequently Asked Questions & Scheme Rules',
    faqDesc: 'Clear, authoritative guidance on MoTA scholarship eligibility, DigiLocker PKI e-KYC, and PFMS direct DBT bank transfers.',
    searchFaqPlaceholder: 'Search FAQs by keyword (e.g. laptop, income limit, DigiLocker, PFMS bank)...',
    allCategories: 'All Categories',
    eligibilityRulesTab: 'Eligibility & Rules',
    digilockerDocsTab: 'DigiLocker & Docs',
    topClassLaptopTab: 'Top Class & Laptop',
    pfmsBankTab: 'PFMS DBT & Bank',
    overseasNosTab: 'Overseas Studies (NOS)',
    stillHaveQuestions: 'Have a specific question about your application or document status?',
    askJagoVoiceAi: 'Ask JAGO Voice Assistant',

    // Login & End-to-End Encryption
    loginTitle: 'Secure Portal Access (E2EE)',
    loginSubtitle: 'Ministry of Tribal Affairs (MoTA) • Government of India',
    loginBadgeOnePortal: 'Unified Single Portal for All 5 MoTA Schemes',
    tabMobileOtp: 'Student Mobile OTP',
    tabApaarDigi: 'APAAR / DigiLocker ID',
    tabOfficerAishe: 'Officer AISHE / Admin',
    e2eeBadge: 'E2EE Cryptographic Handshake Active (TLS 1.3 • AES-256-GCM)',
    e2eeNotice: 'All authentication packets are encrypted at rest and in transit. DPDP Act 2023 Certified.',
    e2eeHandshakeKey: 'Session Key: ECDH-Curve25519 (256-bit)',
    e2eeCipherSuite: 'Cipher: AES-256-GCM • SHA-256 HMAC',
    e2eeAntiReplay: 'Anti-Replay Nonce & Tokenization Active',
    mobileInputLabel: 'Mobile Number (Aadhaar / DBT Linked)',
    mobilePlaceholder: 'Enter 10-digit mobile number',
    enterOtpLabel: 'Enter 6-Digit Secure OTP',
    otpSentNotice: 'A one-time authorization OTP was dispatched to',
    didNotReceiveOtp: "Didn't receive OTP?",
    resendOtpIn: 'Resend in',
    resendOtpNow: 'Resend OTP Now',
    submitOtpVerify: 'Authorize & Sign In Securely',
    sendOtpBtn: 'Generate Secure OTP',
    useDevOtp: 'Use Instant Authorization OTP',
    instantDevOtpBtn: '⚡ Auto-Fill Instant Authorization OTP',
    changePhone: 'Change Phone Number',
    phoneLabelWithPrefix: '+91',
    apaarInputLabel: '12-Digit APAAR / EduID Number',
    apaarPlaceholder: 'e.g. 1234-5678-9012',
    apaarAuthNotice: 'APAAR links directly with your Academic Bank of Credits and DigiLocker documents.',
    apaarVerifyBtn: 'Authenticate via DigiLocker PKI',
    aisheCodeLabel: 'Institution AISHE Code / Directorate ID',
    aishePlaceholder: 'e.g. U-0306 (IIT Bombay)',
    officerPasswordLabel: 'Officer Encryption Password',
    securityPinLabel: '2FA e-Gov Security PIN',
    officerLoginBtn: 'Login to Officer Review Console',
    orQuickDemoPersonas: 'Or 1-Click Demo Evaluation Personas',
    ninePersonasHeader: 'Select Any Persona for Instant Evaluation',

    // Footer
    footerMinistry: 'MINISTRY OF TRIBAL AFFAIRS',
    footerGovt: 'Government of India • जनजातीय कार्य मंत्रालय',
    footerAbout: 'JanjatiSetu - Unified Single-Window Scholarship Discovery & Disbursement Platform for Scheduled Tribe (ST) students across India. Empowering scholars with zero-paperwork DigiLocker e-KYC and direct PFMS bank transfer.',
    dpdpCompliant: 'DPDP Act 2023 Compliant',
    dpdpEncDesc: 'Zero raw Aadhaar storage • AES-256-GCM encryption',
    integratedPortals: 'Integrated National Portals',
    helpdeskContact: 'Helpdesk & Contact',
    downloadMobileApp: 'Download Mobile App',
    installPwa: 'Install Mobile PWA',
    allRightsReserved: 'Ministry of Tribal Affairs (MoTA), Government of India. All Rights Reserved.',
    grievanceRedressal: 'Grievance Redressal',
    privacyPolicy: 'Privacy Policy (DPDP Act)',
    accessibilityStatement: 'Accessibility Statement',
    termsConditions: 'Terms & Conditions'
  }
};

console.log("English base initialized with", Object.keys(TRANSLATIONS.en).length, "keys");
